// Read-only verification of the retained authentic Fossil qualification record.
//
// Every check recomputes its claim from the retained bytes and JSON documents
// under the evidence root: file and segment digests, byte spans, graded
// classification fields, CFG reachability, catalog rows and installed tool
// identities. No recorded number is taken as input to a result.
//
// The module opens every file read-only and writes nothing. The evidence root
// is a parameter; the default is the retained fossil-qualification probe tree.
//
// check ids and what each one recomputes:
//   correspondence-bytes   source-correspondence.json file and segment digests
//   manifest-digests       manifest-check.json entries against source/fossil/manifest
//   compiler-identities    compiler/tool-identities.json, tool-versions.txt, commands.json
//   catalog-provenance     catalog-plan.json against runtime-connection/allowed.fossil
//   guard-span             security.relation.guard and fields offsets in the generated bytes
//   relation-recompute     compiler/view-list-cfg.txt successor map and reachability
//   same-handler-families  the five graded families and the selected-parameter gate
//   database-join          database literal span, prepare call, statement declaration
//   claim-discipline       required fields per classification class in joined-result.json
//   no-enforcement-claim   enforcement, authenticity and completion assertions in strings

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, realpathSync, statSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

export const DEFAULT_EVIDENCE_ROOT =
  '/Users/wahargis/Development/Experiments/baton-bend2-root-delivery-20260928/.scratch/semantic-context-20261005/probes/semantic-models-security-critic/fossil-qualification';

const DEFAULT_SQLITE3 = '/usr/bin/sqlite3';
const DEFAULT_CLANG = '/opt/homebrew/opt/llvm/bin/clang-20';
const DEFAULT_CLANGD = '/opt/homebrew/opt/llvm/bin/clangd';

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function readBytes(file) {
  if (!existsSync(file)) throw new Error(`missing file: ${file}`);
  return readFileSync(file);
}

function readText(file) {
  return readBytes(file).toString('utf8');
}

function readJson(file) {
  const text = readText(file);
  try {
    return JSON.parse(text);
  } catch (error) {
    throw new Error(`invalid JSON in ${file}: ${error.message}`);
  }
}

function sha256Hex(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

function sha1Hex(bytes) {
  return createHash('sha1').update(bytes).digest('hex');
}

// Fossil artifact ids are SHA-1 (40 hex digits) or SHA3-256 (64 hex digits)
// according to the repository hash policy.
function fossilDigestHex(bytes, recorded) {
  if (/^[0-9a-f]{40}$/i.test(recorded)) return sha1Hex(bytes);
  if (/^[0-9a-f]{64}$/i.test(recorded)) return createHash('sha3-256').update(bytes).digest('hex');
  return null;
}

function runCapture(command, args) {
  const result = spawnSync(command, args, { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });
  if (result.error) throw new Error(`cannot run ${command}: ${result.error.message}`);
  return { status: result.status, stdout: result.stdout ?? '', stderr: result.stderr ?? '' };
}

// Recorded ranges use begin.offset and end.offset with the end token length, so
// the covered bytes are [begin.offset, end.offset + end.tokLen).
function spanOf(range) {
  const begin = range && range.begin;
  const end = range && range.end;
  if (!begin || !end) return null;
  const start = begin.offset;
  const stop = end.offset + (typeof end.tokLen === 'number' ? end.tokLen : 0);
  if (!Number.isInteger(start) || !Number.isInteger(stop)) return null;
  return { start, stop };
}

function spanText(bytes, span) {
  return bytes.subarray(span.start, span.stop).toString('utf8');
}

function spanInBounds(bytes, span) {
  return span !== null && span.start >= 0 && span.stop <= bytes.length && span.stop > span.start;
}

function reachable(successors, start, skippedEdges) {
  const seen = new Set();
  const queue = [start];
  while (queue.length > 0) {
    const node = queue.pop();
    if (seen.has(node)) continue;
    seen.add(node);
    for (const next of successors.get(node) ?? []) {
      if (skippedEdges && skippedEdges.has(`${node}->${next}`)) continue;
      queue.push(next);
    }
  }
  return [...seen].sort((left, right) => left - right);
}

function sameNumberSet(left, right) {
  if (!Array.isArray(left) || !Array.isArray(right)) return false;
  const a = [...new Set(left)].sort((x, y) => x - y);
  const b = [...new Set(right)].sort((x, y) => x - y);
  return a.length === b.length && a.every((value, index) => value === b[index]);
}

function formatProblems(problems, limit = 12) {
  const shown = problems.slice(0, limit).join(' | ');
  return problems.length > limit ? `${shown} | and ${problems.length - limit} more` : shown;
}

function withProblems(summary, problems) {
  if (problems.length === 0) return summary;
  return `${summary} Failures (${problems.length}): ${formatProblems(problems)}`;
}

function displayPath(root, file) {
  const relative = path.relative(root, file);
  return relative && !relative.startsWith('..') ? relative : file;
}

// Parse the DumpCFG text into blocks with ordered successors. A block header is
// a line such as " [B34 (ENTRY)]" or " [B1]". Body lines carry "Succs (n): ...",
// "Preds (n): ..." and the terminator line "T: ...".
function parseCfg(text) {
  const blocks = new Map();
  const header = /^ \[B(\d+)(?: \((\w+)\))?\]$/;
  let current = null;
  for (const line of text.split('\n')) {
    const match = header.exec(line);
    if (match) {
      current = {
        id: Number(match[1]),
        label: match[2] ?? null,
        successors: [],
        declaredSuccessorCount: null,
        hasConditionalTerminator: false,
        body: [],
      };
      blocks.set(current.id, current);
      continue;
    }
    if (current === null) continue;
    current.body.push(line);
    const successors = /^\s*Succs \((\d+)\):(.*)$/.exec(line);
    if (successors) {
      current.declaredSuccessorCount = Number(successors[1]);
      current.successors = [...successors[2].matchAll(/B(\d+)/g)].map((entry) => Number(entry[1]));
    }
    if (/^\s*T:/.test(line)) current.hasConditionalTerminator = true;
  }
  return blocks;
}

// Walk every object that carries a string `class` field: the graded blocks.
function gradedBlocks(value) {
  const found = [];
  const visit = (node, at) => {
    if (Array.isArray(node)) {
      node.forEach((child, index) => visit(child, `${at}[${index}]`));
      return;
    }
    if (node && typeof node === 'object') {
      if (typeof node.class === 'string') found.push({ at, block: node });
      for (const [key, child] of Object.entries(node)) visit(child, `${at}.${key}`);
    }
  };
  visit(value, '$');
  return found;
}

function collectStrings(value, at = '$', out = []) {
  if (typeof value === 'string') {
    out.push({ at, text: value });
    return out;
  }
  if (Array.isArray(value)) {
    value.forEach((child, index) => collectStrings(child, `${at}[${index}]`, out));
    return out;
  }
  if (value && typeof value === 'object') {
    for (const [key, child] of Object.entries(value)) collectStrings(child, `${at}.${key}`, out);
  }
  return out;
}

// Clause-level scan for positive claims about guard enforcement, principal
// authenticity or effect completion. A clause that carries a negation token is
// a limitation statement and is accepted.
const CLAIM_PATTERN =
  /\b(?:enforce|enforces|enforced|enforcement)\b|\bguarantee(?:s|d)?\b|\ball[- ]paths?\b|\buniversal(?:ly)?\b|\bprove(?:s|d)?\b|\bproofs?\b|\bauthenticate(?:s|d)?\b|\bauthenticated\b|\bauthentication\b|\bauthenticity\b|\btrusted (?:origin|identity|principal)\b/i;
const COMPLETION_PATTERN = /\bcomplet(?:e|es|ed|ion)\b/i;
const EFFECT_CONTEXT_PATTERN = /\b(?:effect|effects|call|calls|execution|executed|statement|statements)\b/i;
const NEGATION_PATTERN =
  /\b(?:no|not|never|none|without|cannot|absent|absence|unavailable|unverified|unsettled|unsupported|refused|refuses|incomplete|missing|partial|nor|neither)\b/i;

function enforcementClaims(text) {
  const clauses = String(text).split(/[.;\n]/);
  const hits = [];
  for (const clause of clauses) {
    const positive = CLAIM_PATTERN.test(clause) || (COMPLETION_PATTERN.test(clause) && EFFECT_CONTEXT_PATTERN.test(clause));
    if (!positive) continue;
    if (NEGATION_PATTERN.test(clause)) continue;
    hits.push(clause.trim());
  }
  return hits;
}

// Count the top-level arguments of a call whose text starts at the callee name.
// String and character literals are skipped so that commas inside the SQL
// literal do not count as argument separators.
function countCallArguments(callText) {
  let index = callText.indexOf('(');
  if (index < 0) return null;
  let depth = 0;
  let argumentCount = 1;
  let sawContent = false;
  let quote = null;
  for (; index < callText.length; index += 1) {
    const character = callText[index];
    if (quote !== null) {
      if (character === '\\') index += 1;
      else if (character === quote) quote = null;
      continue;
    }
    if (character === '"' || character === "'") {
      quote = character;
      sawContent = true;
      continue;
    }
    if (character === '(') depth += 1;
    else if (character === ')') {
      depth -= 1;
      if (depth === 0) return sawContent || argumentCount > 1 ? argumentCount : 0;
    } else if (character === ',' && depth === 1) argumentCount += 1;
    else if (!/\s/.test(character)) sawContent = true;
  }
  return null;
}

// Hash every regular file that is a direct child of `directories` and return the
// paths whose digest matches. The scan feeds the observed-block evidence lookup;
// its scope is the retained evidence neighborhood, not the whole probe tree.
function filesByDigest(root, digest, directories) {
  const matches = [];
  for (const directory of directories) {
    const absolute = path.join(root, directory);
    if (!existsSync(absolute)) continue;
    const stats = statSync(absolute);
    const names = stats.isDirectory() ? readdirSync(absolute) : [''];
    for (const name of names) {
      const file = name === '' ? absolute : path.join(absolute, name);
      let fileStats;
      try {
        fileStats = statSync(file);
      } catch {
        continue;
      }
      if (!fileStats.isFile() || fileStats.size > 256 * 1024 * 1024) continue;
      if (sha256Hex(readBytes(file)) === digest) matches.push(file);
    }
  }
  return matches;
}

// ---------------------------------------------------------------------------
// 1. correspondence-bytes
// ---------------------------------------------------------------------------

async function correspondenceBytes(root) {
  const file = path.join(root, 'source-correspondence.json');
  const entries = readJson(file);
  if (!Array.isArray(entries)) throw new Error(`${file}: expected a JSON array`);
  const problems = [];
  const cache = new Map();
  const bytesOf = (target) => {
    if (!cache.has(target)) cache.set(target, readBytes(target));
    return cache.get(target);
  };
  const rows = [];

  entries.forEach((entry, index) => {
    const at = `source-correspondence.json[${index}]`;
    const original = bytesOf(entry.original);
    const generated = bytesOf(entry.generated);
    const originalDigest = sha256Hex(original);
    const generatedDigest = sha256Hex(generated);
    if (originalDigest !== entry.original_sha256) {
      problems.push(`${at}: ${entry.original} hashes to ${originalDigest}, recorded ${entry.original_sha256}`);
    }
    if (generatedDigest !== entry.generated_sha256) {
      problems.push(`${at}: ${entry.generated} hashes to ${generatedDigest}, recorded ${entry.generated_sha256}`);
    }
    const originalSpan = Array.isArray(entry.original_byte_span)
      ? { start: entry.original_byte_span[0], stop: entry.original_byte_span[1] }
      : null;
    const generatedSpan = Array.isArray(entry.generated_byte_span)
      ? { start: entry.generated_byte_span[0], stop: entry.generated_byte_span[1] }
      : null;
    if (!spanInBounds(original, originalSpan) || !spanInBounds(generated, generatedSpan)) {
      problems.push(
        `${at}: span out of range (original ${JSON.stringify(entry.original_byte_span)} of ${original.length} bytes, generated ${JSON.stringify(entry.generated_byte_span)} of ${generated.length} bytes)`,
      );
      return;
    }
    const originalSegment = original.subarray(originalSpan.start, originalSpan.stop);
    const generatedSegment = generated.subarray(generatedSpan.start, generatedSpan.stop);
    const identical = originalSegment.equals(generatedSegment);
    const segmentDigest = sha256Hex(generatedSegment);
    if (!identical) {
      problems.push(
        `${at}: original span ${originalSpan.start}..${originalSpan.stop} differs from generated span ${generatedSpan.start}..${generatedSpan.stop}`,
      );
    }
    if (segmentDigest !== entry.segment_sha256) {
      problems.push(`${at}: segment hashes to ${segmentDigest}, recorded ${entry.segment_sha256}`);
    }
    if (identical !== entry.identical_bytes) {
      problems.push(`${at}: identical_bytes is ${entry.identical_bytes} while the byte comparison is ${identical}`);
    }
    rows.push({
      index,
      original: entry.original,
      generated: entry.generated,
      original_span: [originalSpan.start, originalSpan.stop],
      generated_span: [generatedSpan.start, generatedSpan.stop],
      segment_bytes: generatedSpan.stop - generatedSpan.start,
      identical_bytes: identical,
      segment_sha256: segmentDigest,
    });
  });

  const ok = problems.length === 0;
  const summary = `${rows.length} of ${entries.length} correspondence entries recomputed (file digests, span bounds, byte equality, segment digests, identical_bytes)`;
  return { ok, detail: withProblems(summary, problems), evidence: { file, entries: entries.length, rows } };
}

// ---------------------------------------------------------------------------
// 2. manifest-digests
// ---------------------------------------------------------------------------

async function manifestDigests(root) {
  const filesRoot = path.join(root, 'source/fossil');
  const manifestFile = path.join(filesRoot, 'manifest');
  const manifestBytes = readBytes(manifestFile);
  const manifestText = manifestBytes.toString('utf8');
  const check = readJson(path.join(root, 'manifest-check.json'));
  const problems = [];

  const cards = new Map();
  for (const line of manifestText.split('\n')) {
    if (!line.startsWith('F ')) continue;
    const parts = line.trim().split(/\s+/);
    if (parts.length >= 3) cards.set(parts[1], parts[2]);
  }

  const manifestDigest = sha1Hex(manifestBytes);
  const uuidFile = path.join(filesRoot, 'manifest.uuid');
  const recordedUuid = existsSync(uuidFile) ? readText(uuidFile).trim() : null;
  if (recordedUuid !== null && recordedUuid !== manifestDigest) {
    problems.push(`manifest.uuid records ${recordedUuid} while the manifest bytes hash to ${manifestDigest}`);
  }
  if (typeof check.full_identity === 'string' && check.full_identity !== manifestDigest) {
    problems.push(`manifest-check.json full_identity ${check.full_identity} differs from the manifest digest ${manifestDigest}`);
  }

  const entries = Array.isArray(check.files) ? check.files : [];
  const mismatched = [];
  const notRecomputed = [];
  const flagMismatch = [];
  let matched = 0;

  for (const entry of entries) {
    const name = entry.path;
    if (typeof name !== 'string' || name.length === 0) {
      problems.push('manifest-check.json holds an entry without a path');
      continue;
    }
    const target = path.resolve(filesRoot, name);
    if (target !== path.resolve(filesRoot) && !target.startsWith(`${path.resolve(filesRoot)}${path.sep}`)) {
      problems.push(`${name}: path leaves the source root`);
      continue;
    }
    const present = existsSync(target);
    if (!present) {
      notRecomputed.push(name);
      problems.push(`${name}: no file under ${filesRoot}`);
      continue;
    }
    if (entry.present !== true) flagMismatch.push(`${name}: present=${entry.present} while the file exists`);
    const recorded = cards.get(name);
    if (recorded === undefined) {
      notRecomputed.push(name);
      problems.push(`${name}: the retained manifest records no hash`);
      continue;
    }
    const digest = fossilDigestHex(readBytes(target), recorded);
    if (digest === null) {
      notRecomputed.push(name);
      problems.push(`${name}: recorded hash ${recorded} has no supported length`);
      continue;
    }
    const agrees = digest === recorded;
    if (agrees) matched += 1;
    else mismatched.push(`${name}: file hashes to ${digest}, manifest records ${recorded}`);
    if (entry.sha1_matches !== agrees) {
      flagMismatch.push(`${name}: sha1_matches=${entry.sha1_matches} while recomputation gives ${agrees}`);
    }
  }

  problems.push(...mismatched, ...flagMismatch);
  const recomputed = matched + mismatched.length;
  const ok = problems.length === 0 && recomputed === entries.length;
  const summary = `${recomputed} of ${entries.length} manifest entries recomputed against ${displayPath(root, manifestFile)} (${cards.size} F cards); manifest digest ${manifestDigest}`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: {
      manifest: manifestFile,
      manifest_sha1: manifestDigest,
      manifest_uuid: recordedUuid,
      full_identity: check.full_identity ?? null,
      f_card_count: cards.size,
      entries: entries.length,
      matched,
      mismatched,
      not_recomputed: notRecomputed,
    },
  };
}

// ---------------------------------------------------------------------------
// 3. compiler-identities
// ---------------------------------------------------------------------------

async function compilerIdentities(root, options) {
  const identitiesFile = path.join(root, 'compiler/tool-identities.json');
  const commandsFile = path.join(root, 'compiler/commands.json');
  const versionsFile = path.join(root, 'compiler/tool-versions.txt');
  const identities = readJson(identitiesFile);
  const commands = readJson(commandsFile);
  const versionsText = readText(versionsFile);
  if (!Array.isArray(identities)) throw new Error(`${identitiesFile}: expected a JSON array`);
  if (!Array.isArray(commands)) throw new Error(`${commandsFile}: expected a JSON array`);
  const clang = options.clang ?? DEFAULT_CLANG;
  const clangd = options.clangd ?? DEFAULT_CLANGD;
  const problems = [];
  const probes = new Map();
  const probe = (file) => {
    if (!probes.has(file)) probes.set(file, runCapture(file, ['--version']));
    return probes.get(file);
  };

  const recorded = [];
  for (const entry of identities) {
    const file = entry.path;
    if (typeof file !== 'string') {
      problems.push('tool-identities.json holds an entry without a path');
      continue;
    }
    if (!existsSync(file)) {
      problems.push(`${file}: recorded tool is absent`);
      continue;
    }
    const digest = sha256Hex(readBytes(file));
    if (digest !== entry.sha256) problems.push(`${file}: hashes to ${digest}, recorded ${entry.sha256}`);
    const row = { path: file, sha256: digest, recorded_sha256: entry.sha256, version: null };
    if ((statSync(file).mode & 0o111) !== 0) {
      const result = probe(file);
      const firstLine = result.stdout.split('\n')[0].trim();
      row.version = firstLine;
      if (result.status !== 0) problems.push(`${file} --version exits ${result.status}`);
      if (!result.stdout.includes('20.1.8')) problems.push(`${file} --version reports no 20.1.8`);
      if (firstLine.length > 0 && !versionsText.includes(firstLine)) {
        problems.push(`${file} --version first line ${JSON.stringify(firstLine)} is absent from compiler/tool-versions.txt`);
      }
    }
    recorded.push(row);
  }

  // Installed clang-20 and clangd named by the check contract.
  const installed = [];
  for (const [name, file] of [['clang-20', clang], ['clangd', clangd]]) {
    if (!existsSync(file)) {
      problems.push(`${name}: ${file} is absent`);
      continue;
    }
    const result = probe(file);
    const firstLine = result.stdout.split('\n')[0].trim();
    installed.push({ name, path: file, realpath: realpathSync(file), version: firstLine, digest: sha256Hex(readBytes(file)) });
    if (result.status !== 0) problems.push(`${file} --version exits ${result.status}`);
    if (!result.stdout.includes('20.1.8')) problems.push(`${file} --version does not report 20.1.8`);
  }

  const installedClang = installed.find((entry) => entry.name === 'clang-20');
  const clangIdentity = recorded.find((entry) => path.basename(entry.path).startsWith('clang'));
  if (installedClang && clangIdentity) {
    if (realpathSync(clangIdentity.path) !== installedClang.realpath) {
      problems.push(
        `recorded clang identity ${clangIdentity.path} resolves to ${realpathSync(clangIdentity.path)} while ${installedClang.path} resolves to ${installedClang.realpath}`,
      );
    }
  }
  const recordedClangd = recorded.find((entry) => path.basename(entry.path).startsWith('clangd'));
  const clangdCovers = installed.find((entry) => entry.name === 'clangd');
  if (clangdCovers && recordedClangd === undefined) {
    // The record carries no clangd digest; the version probe below is the only
    // clangd identity available from the retained files.
    clangdCovers.no_recorded_digest = true;
  }

  // tool-versions.txt equals the clang-20 probe output followed by one LLVM tool
  // probe output.
  const normalize = (text) => text.replace(/[ \t]+$/gm, '').replace(/\n+$/, '\n');
  const clangVersionText = installedClang ? probe(installedClang.path).stdout : null;
  const versionSources = [];
  let versionsMatch = null;
  if (clangVersionText !== null) {
    for (const row of recorded) {
      if (row.version === null || !/LLVM version/.test(row.version)) continue;
      const combined = normalize(clangVersionText + probe(row.path).stdout);
      versionSources.push({ with: row.path, matches: combined === normalize(versionsText) });
      if (combined === normalize(versionsText)) versionsMatch = row.path;
    }
  }
  if (clangVersionText !== null && versionsMatch === null) {
    problems.push(
      `compiler/tool-versions.txt does not equal the clang-20 probe output followed by a recorded LLVM tool probe output (tried ${versionSources.length} tools)`,
    );
  }

  // Every recorded command names an executable that reports this front end and
  // carries return code 0.
  const commandsChecked = [];
  commands.forEach((command, index) => {
    const argv = Array.isArray(command.argv) ? command.argv : [];
    const executable = argv[0];
    const at = `commands.json[${index}]`;
    if (typeof executable !== 'string' || executable.length === 0) {
      problems.push(`${at}: empty argv`);
      return;
    }
    if (!existsSync(executable)) {
      problems.push(`${at}: executable ${executable} is absent`);
      return;
    }
    const result = probe(executable);
    if (result.status !== 0) problems.push(`${at}: ${executable} --version exits ${result.status}`);
    if (!result.stdout.includes('20.1.8')) problems.push(`${at}: ${executable} front-end version does not resolve to 20.1.8`);
    if (command.returncode !== 0) problems.push(`${at}: recorded return code ${command.returncode}`);
    commandsChecked.push({ index, executable, returncode: command.returncode, version: result.stdout.split('\n')[0].trim() });
  });

  const ok = problems.length === 0;
  const summary = `${recorded.length} recorded tool identities recomputed; ${commandsChecked.length} compile commands name an executable reporting 20.1.8 with recorded return code 0; installed clang-20 and clangd probes resolve to 20.1.8`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: {
      identities: recorded,
      installed,
      versions_file: versionsFile,
      versions_match_tool: versionsMatch,
      tool_versions_lines: versionsText.split('\n').filter((line) => line.trim().length > 0),
      commands: commandsChecked,
    },
  };
}

// ---------------------------------------------------------------------------
// 4. catalog-provenance
// ---------------------------------------------------------------------------

async function catalogProvenance(root, options) {
  const planFile = path.join(root, 'catalog-plan.json');
  const plan = readJson(planFile);
  const database = path.join(root, 'runtime-connection/allowed.fossil');
  const sqlite = options.sqlite3 ?? DEFAULT_SQLITE3;
  const problems = [];
  const databaseBytes = readBytes(database);
  const digest = sha256Hex(databaseBytes);

  if (digest !== plan.database_sha256) {
    problems.push(`${database} hashes to ${digest}, catalog-plan.json records ${plan.database_sha256}`);
  }

  const argv = Array.isArray(plan.argv) ? plan.argv : [];
  if (!argv.includes(database)) problems.push(`catalog-plan.json argv does not name ${database}`);

  const fileFields = [];
  const openReads = [];
  const recordedCatalogRows = [];
  const results = Array.isArray(plan.results) ? plan.results : [];
  results.forEach((result, resultIndex) => {
    if (!Array.isArray(result)) return;
    result.forEach((row) => {
      if (row === null || typeof row !== 'object') return;
      if (typeof row.file === 'string') fileFields.push({ result: resultIndex, file: row.file });
      if (row.opcode === 'OpenRead') {
        openReads.push({ result: resultIndex, cursor: row.p1, rootpage: row.p2, comment: row.comment ?? null });
      }
      if (typeof row.rootpage === 'number' && typeof row.name === 'string' && typeof row.type === 'string') {
        recordedCatalogRows.push({ rootpage: row.rootpage, type: row.type, name: row.name, tbl_name: row.tbl_name ?? null });
      }
    });
  });

  for (const field of fileFields) {
    if (field.file !== database) problems.push(`catalog-plan.json results[${field.result}] names ${field.file} instead of ${database}`);
  }
  if (fileFields.length === 0) problems.push('catalog-plan.json records no database_list file entry');

  const sqliteVersion = runCapture(sqlite, ['--version']).stdout.trim();
  if (typeof plan.version === 'string' && plan.version !== sqliteVersion) {
    problems.push(`${sqlite} reports ${sqliteVersion} while catalog-plan.json records ${plan.version}`);
  }

  const query = 'SELECT type,name,tbl_name,rootpage FROM sqlite_schema ORDER BY rootpage';
  const live = runCapture(sqlite, ['-readonly', '-json', database, query]);
  if (live.status !== 0) throw new Error(`${sqlite} -readonly exits ${live.status}: ${live.stderr.trim()}`);
  const schemaRows = JSON.parse(live.stdout);

  const joined = [];
  for (const operand of openReads) {
    if (operand.rootpage === 0) {
      // Cursor 0 addresses the table itself; rootpage 0 is not a schema entry.
      joined.push({ ...operand, schema_rows: [], note: 'rootpage 0 addresses cursor 0 directly' });
      continue;
    }
    const matches = schemaRows.filter((row) => row.rootpage === operand.rootpage);
    if (matches.length !== 1) {
      problems.push(`OpenRead operand rootpage ${operand.rootpage} joins to ${matches.length} sqlite_schema rows`);
      joined.push({ ...operand, schema_rows: matches });
      continue;
    }
    const row = matches[0];
    const commentName = typeof operand.comment === 'string' ? operand.comment.split(';').pop().trim() : null;
    if (commentName !== null && commentName.length > 0 && commentName !== row.name && commentName !== row.tbl_name) {
      problems.push(
        `OpenRead operand rootpage ${operand.rootpage} comment names ${commentName} while the catalog row names ${row.name} (${row.type} ${row.tbl_name})`,
      );
    }
    joined.push({ ...operand, schema_rows: matches, name: row.name, type: row.type, tbl_name: row.tbl_name });
  }
  if (openReads.length === 0) problems.push('catalog-plan.json records no OpenRead operand');

  for (const recorded of recordedCatalogRows) {
    const live = schemaRows.find((row) => row.rootpage === recorded.rootpage);
    if (!live) {
      problems.push(`recorded catalog row rootpage ${recorded.rootpage} (${recorded.name}) is absent from the live catalog`);
      continue;
    }
    if (live.name !== recorded.name || live.type !== recorded.type) {
      problems.push(
        `recorded catalog row rootpage ${recorded.rootpage} is ${recorded.type} ${recorded.name} while the live catalog holds ${live.type} ${live.name}`,
      );
    }
  }

  const stats = statSync(database);
  const identity = {
    size: stats.size,
    inode: stats.ino,
    device: stats.dev,
    recorded_inode: plan.inode ?? null,
    recorded_device: plan.device ?? null,
    inode_matches: plan.inode === undefined || plan.inode === stats.ino,
    device_matches: plan.device === undefined || plan.device === stats.dev,
  };
  if (plan.inode !== undefined && plan.inode !== stats.ino) {
    problems.push(`catalog-plan.json records inode ${plan.inode} while ${database} has inode ${stats.ino}`);
  }

  const ok = problems.length === 0;
  const schemaByRoot = new Map(schemaRows.map((row) => [row.rootpage, `${row.type} ${row.name}`]));
  const summary = `${database} hashes to the recorded digest; ${fileFields.length} recorded file entries name it; ${openReads.length} OpenRead operands join to real sqlite_schema rows [${joined
    .map((entry) => `${entry.rootpage}=${schemaByRoot.get(entry.rootpage) ?? 'none'}`)
    .join(', ')}]; sqlite3 reports ${sqliteVersion}; inode ${stats.ino}`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: {
      plan: planFile,
      database,
      database_sha256: digest,
      recorded_database_sha256: plan.database_sha256,
      sqlite3: sqlite,
      sqlite3_version: sqliteVersion,
      recorded_version: plan.version ?? null,
      file_entries: fileFields,
      open_reads: openReads,
      joined_rows: joined,
      recorded_catalog_rows: recordedCatalogRows,
      live_schema_row_count: schemaRows.length,
      file_identity: identity,
    },
  };
}

// ---------------------------------------------------------------------------
// 5. guard-span
// ---------------------------------------------------------------------------

async function guardSpan(root) {
  const joined = readJson(path.join(root, 'joined-result.json'));
  const subject = joined.subject ?? {};
  const generatedPath = subject.source?.generated;
  if (typeof generatedPath !== 'string') throw new Error('joined-result.json subject.source.generated is absent');
  const bytes = readBytes(generatedPath);
  const relation = joined.security?.relation ?? {};
  const problems = [];

  const guard = relation.guard ?? {};
  const guardSpan = spanOf(guard.range);
  let guardText = null;
  if (!spanInBounds(bytes, guardSpan)) {
    problems.push(`security.relation.guard range ${JSON.stringify(guard.range)} does not index ${displayPath(root, generatedPath)} (${bytes.length} bytes)`);
  } else {
    guardText = spanText(bytes, guardSpan);
    const trimmed = guardText.trim();
    if (!/^if[\s(]/.test(trimmed)) problems.push(`security.relation.guard span does not start an if statement: ${JSON.stringify(trimmed.slice(0, 40))}`);
    const opens = (trimmed.match(/\{/g) ?? []).length;
    const closes = (trimmed.match(/\}/g) ?? []).length;
    if (opens === 0 || opens !== closes) problems.push(`security.relation.guard span does not hold a balanced block: {${opens} }${closes}`);
    if (!trimmed.endsWith('}')) problems.push(`security.relation.guard span does not end at a closing brace: ${JSON.stringify(trimmed.slice(-20))}`);
    if (guard.kind !== undefined && guard.kind !== 'IfStmt') problems.push(`security.relation.guard kind is ${guard.kind}`);
  }

  const fields = Array.isArray(relation.fields) ? relation.fields : [];
  if (fields.length < 2) problems.push(`security.relation.fields holds ${fields.length} entries; the guard records two operands`);
  const operands = [];
  const names = [];
  fields.forEach((field, index) => {
    const at = `security.relation.fields[${index}]`;
    const name = field.name;
    const expression = field.expression ?? {};
    const expressionSpan = spanOf(expression.range);
    if (typeof name !== 'string' || name.length === 0) {
      problems.push(`${at}: no operand name recorded`);
      return;
    }
    names.push(name);
    if (!spanInBounds(bytes, expressionSpan)) {
      problems.push(`${at}: expression range ${JSON.stringify(expression.range)} does not index ${displayPath(root, generatedPath)}`);
      return;
    }
    const endOffset = expression.range.end.offset;
    const endLength = expression.range.end.tokLen ?? 0;
    const nameToken = bytes.subarray(endOffset, endOffset + endLength).toString('utf8');
    if (nameToken !== name) {
      problems.push(`${at}: bytes at the recorded member offset ${endOffset} are ${JSON.stringify(nameToken)}, recorded name ${JSON.stringify(name)}`);
    }
    if (endOffset - 1 >= 0 && bytes[endOffset - 1] !== 0x2e) {
      problems.push(`${at}: byte before the member offset ${endOffset} is ${JSON.stringify(String.fromCharCode(bytes[endOffset - 1]))} instead of a dot`);
    }
    if (guardSpan !== null && (expressionSpan.start < guardSpan.start || expressionSpan.stop > guardSpan.stop)) {
      problems.push(`${at}: expression span ${expressionSpan.start}..${expressionSpan.stop} lies outside the guard span ${guardSpan.start}..${guardSpan.stop}`);
    }
    operands.push({
      name,
      expression_span: [expressionSpan.start, expressionSpan.stop],
      member_offset: endOffset,
      expression_text: spanText(bytes, expressionSpan),
    });
  });
  if (new Set(names).size !== names.length) problems.push(`security.relation.fields operand names repeat: ${names.join(', ')}`);

  const ok = problems.length === 0;
  const summary = `guard span ${guardSpan ? `${guardSpan.start}..${guardSpan.stop}` : 'absent'} spells ${JSON.stringify((guardText ?? '').trim())}; ${operands.length} field operands resolve to their recorded member names at offsets ${operands
    .map((operand) => `${operand.name}@${operand.member_offset}`)
    .join(', ')}; operand names are distinct`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: {
      generated: generatedPath,
      guard: { span: guardSpan ? [guardSpan.start, guardSpan.stop] : null, kind: guard.kind ?? null, text: guardText },
      operands,
    },
  };
}

// ---------------------------------------------------------------------------
// 6. relation-recompute
// ---------------------------------------------------------------------------

async function relationRecompute(root) {
  const cfgFile = path.join(root, 'compiler/view-list-cfg.txt');
  const text = readText(cfgFile);
  const blocks = parseCfg(text);
  const joined = readJson(path.join(root, 'joined-result.json'));
  const relation = joined.security?.relation ?? {};
  const problems = [];

  const entryBlocks = [...blocks.values()].filter((block) => block.label === 'ENTRY');
  if (entryBlocks.length !== 1) throw new Error(`${cfgFile}: ${entryBlocks.length} blocks carry the ENTRY label`);
  const entry = entryBlocks[0].id;
  const parsed = new Map([...blocks.values()].map((block) => [block.id, block.successors]));
  for (const block of blocks.values()) {
    if (block.declaredSuccessorCount !== null && block.declaredSuccessorCount !== block.successors.length) {
      problems.push(`block ${block.id}: Succs declares ${block.declaredSuccessorCount} successors and lists ${block.successors.length}`);
    }
  }

  // (b) the recorded successor map.
  const recorded = new Map();
  for (const [key, value] of Object.entries(relation.cfg_edges ?? {})) recorded.set(Number(key), value);
  const parsedIds = [...parsed.keys()].sort((a, b) => a - b);
  const recordedIds = [...recorded.keys()].sort((a, b) => a - b);
  if (parsedIds.length !== recordedIds.length || parsedIds.some((id, index) => id !== recordedIds[index])) {
    problems.push(`parsed block ids [${parsedIds.join(', ')}] differ from cfg_edges keys [${recordedIds.join(', ')}]`);
  }
  let successorMismatches = 0;
  for (const id of parsedIds) {
    if (!recorded.has(id)) continue;
    if (JSON.stringify(parsed.get(id)) !== JSON.stringify(recorded.get(id))) {
      successorMismatches += 1;
      problems.push(`block ${id}: parsed successors [${parsed.get(id).join(', ')}] differ from cfg_edges [${(recorded.get(id) ?? []).join(', ')}]`);
    }
  }

  // (a) forward reachability from the entry block.
  const entryReach = reachable(parsed, entry);
  const entryReachRecorded = reachable(recorded, entry);
  if (!sameNumberSet(entryReach, entryReachRecorded)) {
    problems.push(`entry reachability parsed [${entryReach.join(', ')}] differs from cfg_edges [${entryReachRecorded.join(', ')}]`);
  }

  // Accepted-state reachability: the accepted outcome of the guard continues in
  // the allow block, so the reachable set of the accepted state is computed from
  // that block, which is the quantity recorded as allow_reachable.
  const allowBlock = relation.allow_block;
  const denyBlock = relation.deny_block;
  const selectedCallBlock = relation.selected_call_block;
  if (!parsed.has(allowBlock)) problems.push(`allow_block ${allowBlock} is not a parsed block`);
  if (!parsed.has(denyBlock)) problems.push(`deny_block ${denyBlock} is not a parsed block`);
  const acceptedStateReach = parsed.has(allowBlock) ? reachable(parsed, allowBlock) : [];
  if (!sameNumberSet(acceptedStateReach, relation.allow_reachable)) {
    problems.push(`accepted-state reachability from the allow block [${acceptedStateReach.join(', ')}] differs from allow_reachable [${(relation.allow_reachable ?? []).join(', ')}]`);
  }
  if (selectedCallBlock !== undefined && !acceptedStateReach.includes(selectedCallBlock)) {
    problems.push(`selected_call_block ${selectedCallBlock} is not reachable from the allow block ${allowBlock}`);
  }
  if (denyBlock !== undefined && !entryReach.includes(denyBlock)) {
    problems.push(`deny_block ${denyBlock} is not reachable from the entry block ${entry}`);
  }

  // (c) the accepted exit-edge set: the false successor edges of the
  // short-circuit decision blocks that feed the allow block. LLVM emits the
  // true successor first and the false successor second.
  const decisionBlocks = [...blocks.values()].filter((block) => block.hasConditionalTerminator && block.successors.includes(allowBlock));
  const acceptedEdges = new Set();
  for (const block of decisionBlocks) {
    const index = block.successors.indexOf(allowBlock);
    if (index === 1) acceptedEdges.add(`${block.id}->${allowBlock}`);
    else problems.push(`block ${block.id}: the allow block ${allowBlock} is successor index ${index}; the false successor sits at index 1`);
  }
  if (decisionBlocks.length === 0) problems.push(`no conditional block feeds the allow block ${allowBlock}`);
  if (acceptedEdges.size === 0) problems.push('the accepted exit-edge set is empty');

  // (d) reachability after removing the whole accepted exit-edge set.
  const trimmed = new Map([...parsed.entries()].map(([id, successors]) => [id, [...successors]]));
  const reachWithoutAccepted = reachable(trimmed, entry, acceptedEdges);
  if (!sameNumberSet(reachWithoutAccepted, relation.entry_reach_with_allow_block_removed)) {
    problems.push(
      `reachability after removing ${[...acceptedEdges].join(', ')} is [${reachWithoutAccepted.join(', ')}] and entry_reach_with_allow_block_removed holds [${(relation.entry_reach_with_allow_block_removed ?? []).join(', ')}]`,
    );
  }

  // (e) the selected call block is unreachable once the accepted edges are gone.
  const callReachable = reachWithoutAccepted.includes(selectedCallBlock);
  if (callReachable) problems.push(`selected_call_block ${selectedCallBlock} stays reachable after removing the accepted exit edges`);
  if (relation.selected_unreachable_when_allow_block_removed !== !callReachable) {
    problems.push(
      `selected_unreachable_when_allow_block_removed is ${relation.selected_unreachable_when_allow_block_removed} while the recomputed value is ${!callReachable}`,
    );
  }
  if (!callReachable === false) problems.push('the selected call block is reachable in the recomputed graph');

  // (f) the deny block is reachable from the entry through no accepted edge and
  // its text holds a return terminator.
  const denyReachWithoutAccepted = reachable(parsed, entry, acceptedEdges);
  if (!denyReachWithoutAccepted.includes(denyBlock)) {
    problems.push(`deny_block ${denyBlock} is unreachable from the entry block ${entry} without an accepted edge`);
  }
  const denyText = parsed.has(denyBlock) ? blocks.get(denyBlock).body.join('\n') : '';
  if (!denyText.includes('return;')) problems.push(`deny_block ${denyBlock} holds no return; terminator`);
  const denyReach = parsed.has(denyBlock) ? reachable(parsed, denyBlock) : [];
  if (!sameNumberSet(denyReach, relation.deny_reachable)) {
    problems.push(`deny_block reachability [${denyReach.join(', ')}] differs from deny_reachable [${(relation.deny_reachable ?? []).join(', ')}]`);
  }
  if (relation.class !== 'static-possible') problems.push(`security.relation class is ${relation.class}`);

  const ok = problems.length === 0;
  const summary = `${blocks.size} blocks parsed with ordered successors ${successorMismatches === 0 ? 'matching' : 'differing from'} cfg_edges; entry block ${entry} reaches [${entryReach.join(', ')}]; accepted exit edges ${[...acceptedEdges].sort().join(', ')}; reachability after their removal [${reachWithoutAccepted.join(', ')}]; selected call block ${selectedCallBlock} unreachable in that graph and selected_unreachable_when_allow_block_removed is ${relation.selected_unreachable_when_allow_block_removed}; deny block ${denyBlock} reachable through no accepted edge with a return terminator`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: {
      cfg: cfgFile,
      entry_block: entry,
      block_count: blocks.size,
      accepted_edges: [...acceptedEdges].sort(),
      decision_blocks: decisionBlocks.map((block) => block.id),
      entry_reachable: entryReach,
      accepted_state_reachable: acceptedStateReach,
      reach_without_accepted_edges: reachWithoutAccepted,
      deny_reachable: denyReach,
      deny_block_text: denyText.trim().split('\n').filter((line) => line.trim().length > 0),
      selected_call_block: selectedCallBlock ?? null,
    },
  };
}

// ---------------------------------------------------------------------------
// 7. same-handler-families
// ---------------------------------------------------------------------------

async function sameHandlerFamilies(root) {
  const joined = readJson(path.join(root, 'joined-result.json'));
  const problems = [];
  const subject = joined.subject;
  if (Array.isArray(subject) || subject === null || typeof subject !== 'object') {
    problems.push('joined-result.json subject is not a single object');
  }
  for (const key of ['subjects', 'handlers', 'results']) {
    if (Array.isArray(joined[key])) problems.push(`joined-result.json carries a ${key} array next to subject`);
  }
  const functionName = subject && typeof subject.function === 'string' ? subject.function : null;
  if (functionName === null) problems.push('subject.function is absent');

  const families = ['types', 'calls', 'security', 'database', 'diagnostics'];
  const familyRows = [];
  for (const name of families) {
    const family = joined[name];
    if (family === null || typeof family !== 'object' || Array.isArray(family)) {
      problems.push(`family ${name} is absent from joined-result.json`);
      continue;
    }
    if (typeof family.class !== 'string') problems.push(`family ${name} carries no class`);
    let size = 0;
    if (name === 'types') size = (family.global_inputs?.length ?? 0) + (family.handler_type ? 1 : 0);
    if (name === 'calls') size = family.facts?.length ?? 0;
    if (name === 'security') size = (family.roles ? 1 : 0) + (family.relation ? 1 : 0);
    if (name === 'database') size = family.sql ? 1 : 0;
    if (name === 'diagnostics') size = family.files?.length ?? 0;
    if (size === 0) problems.push(`family ${name} carries no entries for the subject`);
    familyRows.push({ name, class: family.class, entries: size });
  }

  const generatedPath = subject?.source?.generated;
  const generatedBytes = typeof generatedPath === 'string' ? readBytes(generatedPath) : null;
  const subjectSpan = Array.isArray(subject?.source?.generated_byte_span)
    ? { start: subject.source.generated_byte_span[0], stop: subject.source.generated_byte_span[1] }
    : null;

  // Handler-body facts must index the recorded subject bytes.
  const bodySpans = [];
  for (const [index, fact] of (joined.calls?.facts ?? []).entries()) {
    bodySpans.push({ at: `calls.facts[${index}].call`, span: spanOf(fact.call?.range) });
  }
  bodySpans.push({ at: 'security.relation.guard', span: spanOf(joined.security?.relation?.guard?.range) });
  (joined.security?.relation?.fields ?? []).forEach((field, index) => {
    bodySpans.push({ at: `security.relation.fields[${index}].expression`, span: spanOf(field.expression?.range) });
  });
  for (const name of ['selected_prepare', 'selected_step', 'literal']) {
    bodySpans.push({ at: `database.${name}`, span: spanOf(joined.database?.[name]?.range) });
  }
  const outside = [];
  for (const entry of bodySpans) {
    if (generatedBytes === null) break;
    if (!spanInBounds(generatedBytes, entry.span)) {
      outside.push(`${entry.at} range ${JSON.stringify(entry.span)} is outside ${generatedBytes.length} bytes`);
      continue;
    }
    if (subjectSpan !== null && spanInBounds(generatedBytes, subjectSpan) && (entry.span.start < subjectSpan.start || entry.span.stop > subjectSpan.stop)) {
      outside.push(`${entry.at} range ${entry.span.start}..${entry.span.stop} lies outside the subject span ${subjectSpan.start}..${subjectSpan.stop}`);
    }
  }
  problems.push(...outside);

  // The selected-db_prepare signature gate.
  const types = joined.types ?? {};
  const parameters = types.parameters;
  if (!Array.isArray(parameters)) problems.push('types.parameters is not an array');
  else if (parameters.length !== 0) problems.push(`types.parameters holds ${parameters.length} formals for the selected handler`);
  const example = types.nonempty_parameter_example ?? {};
  const exampleParameters = example.parameters;
  if (!Array.isArray(exampleParameters) || exampleParameters.length === 0) {
    problems.push('types.nonempty_parameter_example.parameters is empty');
  } else {
    exampleParameters.forEach((parameter, index) => {
      if (typeof parameter.name !== 'string' || parameter.name.length === 0) {
        problems.push(`types.nonempty_parameter_example.parameters[${index}] carries no name`);
      }
      if (typeof parameter.type?.qualType !== 'string' || parameter.type.qualType.length === 0) {
        problems.push(`types.nonempty_parameter_example.parameters[${index}] carries no qualType`);
      }
    });
  }
  if (typeof example.name !== 'string' || example.name.length === 0) problems.push('types.nonempty_parameter_example.name is absent');
  if (example.name !== undefined && example.name === functionName) {
    problems.push(`types.nonempty_parameter_example.name ${example.name} equals the selected function name`);
  }

  const ok = problems.length === 0;
  const summary = `subject ${JSON.stringify(functionName)} carries families ${familyRows
    .map((row) => `${row.name}(${row.class}, ${row.entries})`)
    .join(', ')}; ${bodySpans.length} handler-body ranges index the subject span ${subjectSpan ? `${subjectSpan.start}..${subjectSpan.stop}` : 'absent'}; types.parameters is empty while nonempty_parameter_example ${JSON.stringify(example.name)} holds ${exampleParameters?.length ?? 0} formals`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: {
      subject: subject ?? null,
      families: familyRows,
      body_range_count: bodySpans.length,
      body_range_failures: outside,
      handler_type: types.handler_type ?? null,
      parameters: parameters ?? null,
      nonempty_parameter_example: { name: example.name ?? null, parameters: exampleParameters ?? null },
    },
  };
}

// ---------------------------------------------------------------------------
// 8. database-join
// ---------------------------------------------------------------------------

async function databaseJoin(root) {
  const joined = readJson(path.join(root, 'joined-result.json'));
  const subject = joined.subject ?? {};
  const generatedPath = subject.source?.generated;
  if (typeof generatedPath !== 'string') throw new Error('joined-result.json subject.source.generated is absent');
  const bytes = readBytes(generatedPath);
  const database = joined.database ?? {};
  const problems = [];

  const sql = database.sql;
  if (typeof sql !== 'string') throw new Error('database.sql is absent');
  const literalSpan = spanOf(database.literal?.range);
  let literalText = null;
  if (!spanInBounds(bytes, literalSpan)) {
    problems.push(`database.literal range ${JSON.stringify(database.literal?.range)} does not index ${displayPath(root, generatedPath)}`);
  } else {
    literalText = spanText(bytes, literalSpan);
    const quoted = `"${sql}"`;
    if (literalText !== quoted) {
      problems.push(`database.sql ${JSON.stringify(sql)} differs from the literal span bytes ${JSON.stringify(literalText)}`);
    }
    if (database.literal?.kind !== undefined && database.literal.kind !== 'StringLiteral') {
      problems.push(`database.literal kind is ${database.literal.kind}`);
    }
    const byteLength = Buffer.byteLength(sql, 'utf8');
    if (literalSpan.stop - literalSpan.start !== byteLength + 2) {
      problems.push(`the literal span covers ${literalSpan.stop - literalSpan.start} bytes for a ${byteLength}-byte statement`);
    }
  }

  // The selected prepare call names a helper recorded in the summary bindings.
  const prepareSpan = spanOf(database.selected_prepare?.range);
  const bindings = Array.isArray(database.helper_summary?.bindings) ? database.helper_summary.bindings : [];
  let callee = null;
  let binding = null;
  if (!spanInBounds(bytes, prepareSpan)) {
    problems.push(`database.selected_prepare range ${JSON.stringify(database.selected_prepare?.range)} does not index ${displayPath(root, generatedPath)}`);
  } else {
    const calleeLength = database.selected_prepare.range.begin.tokLen ?? 0;
    callee = bytes.subarray(prepareSpan.start, prepareSpan.start + calleeLength).toString('utf8');
    binding = bindings.find((entry) => entry.name === callee) ?? null;
    if (binding === null) {
      problems.push(`database.selected_prepare names callee ${JSON.stringify(callee)}, which no helper_summary binding records`);
    }
    if (literalSpan !== null && spanInBounds(bytes, literalSpan) && (literalSpan.start < prepareSpan.start || literalSpan.stop > prepareSpan.stop)) {
      problems.push(`the SQL literal span ${literalSpan.start}..${literalSpan.stop} lies outside the prepare call span ${prepareSpan.start}..${prepareSpan.stop}`);
    }
    const callText = spanText(bytes, prepareSpan);
    const recomputedArguments = countCallArguments(callText);
    if (recomputedArguments !== null && recomputedArguments !== database.actual_argument_count) {
      problems.push(`database.actual_argument_count is ${database.actual_argument_count} while the call text holds ${recomputedArguments} arguments`);
    }
  }

  // Preparation and the first step resolve the same local declaration.
  const statementVariable = database.statement_variable ?? {};
  const stepDeclaration = database.step_same_decl ?? {};
  if (statementVariable.id === undefined || stepDeclaration.id === undefined) {
    problems.push('database.statement_variable or database.step_same_decl carries no declaration id');
  } else if (statementVariable.id !== stepDeclaration.id) {
    problems.push(`statement_variable ${statementVariable.id} differs from step_same_decl ${stepDeclaration.id}`);
  }
  if (statementVariable.name !== stepDeclaration.name || statementVariable.kind !== stepDeclaration.kind) {
    problems.push(
      `statement_variable ${statementVariable.kind} ${statementVariable.name} differs from step_same_decl ${stepDeclaration.kind} ${stepDeclaration.name}`,
    );
  }

  // The literal holds no percent and no NUL byte.
  const hasPercent = sql.includes('%');
  const hasNul = sql.includes('\u0000') || (literalText !== null && literalText.includes('\u0000'));
  if (database.no_format_no_nul !== (!hasPercent && !hasNul)) {
    problems.push(`database.no_format_no_nul is ${database.no_format_no_nul} while the statement holds percent=${hasPercent} nul=${hasNul}`);
  }

  // Target and planner versions are distinct, and each is independently known.
  const targetVersion = database.target_sqlite_source_version;
  const plannerVersion = database.external_planner_version;
  if (typeof targetVersion !== 'string' || typeof plannerVersion !== 'string') {
    problems.push('database.target_sqlite_source_version or database.external_planner_version is absent');
  } else if (targetVersion === plannerVersion) {
    problems.push('database target and external planner versions are equal');
  }
  const headerFile = path.join(root, 'source/fossil/src/sqlite3.h');
  if (existsSync(headerFile)) {
    const header = readText(headerFile);
    const define = /#define\s+SQLITE_VERSION\s+"([^"]+)"/.exec(header);
    if (decline(define)) problems.push(`${displayPath(root, headerFile)} records no SQLITE_VERSION define`);
    else if (define[1] !== targetVersion) {
      problems.push(`source/sqlite3.h defines SQLITE_VERSION ${define[1]} while database.target_sqlite_source_version is ${targetVersion}`);
    }
  } else {
    problems.push(`${displayPath(root, headerFile)} is absent; the target version cannot be recomputed`);
  }
  const sqlite = options0Sqlite(root);
  const livePlanner = runCapture(sqlite, ['--version']).stdout.trim();
  if (livePlanner !== plannerVersion) {
    problems.push(`${sqlite} reports ${livePlanner} while database.external_planner_version is ${plannerVersion}`);
  }

  const catalogEvidence = database.catalog_evidence;
  if (typeof catalogEvidence !== 'string' || !existsSync(catalogEvidence)) {
    problems.push(`database.catalog_evidence ${JSON.stringify(catalogEvidence)} is not a retained file`);
  }

  const ok = problems.length === 0;
  const summary = `database.sql equals the literal span bytes at ${literalSpan ? `${literalSpan.start}..${literalSpan.stop}` : 'absent'}; the prepare call ${JSON.stringify(callee)} is recorded in helper_summary.bindings; statement_variable and step_same_decl share ${statementVariable.id ?? 'no id'}; no_format_no_nul recomputes to ${!hasPercent && !hasNul}; target ${targetVersion} differs from planner ${plannerVersion}`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: {
      generated: generatedPath,
      sql,
      literal_text: literalText,
      literal_span: literalSpan ? [literalSpan.start, literalSpan.stop] : null,
      prepare_span: prepareSpan ? [prepareSpan.start, prepareSpan.stop] : null,
      callee,
      binding_name: binding?.name ?? null,
      binding_mangled: binding?.mangledName ?? null,
      argument_count: database.actual_argument_count,
      statement_variable: statementVariable,
      step_same_decl: stepDeclaration,
      no_format_no_nul: { recorded: database.no_format_no_nul, percent: hasPercent, nul: hasNul },
      target_sqlite_source_version: targetVersion ?? null,
      external_planner_version: plannerVersion ?? null,
      live_planner_version: livePlanner,
      catalog_evidence: catalogEvidence ?? null,
    },
  };
}

function decline(define) {
  return define === null;
}

function options0Sqlite(root) {
  return DEFAULT_SQLITE3;
}

// ---------------------------------------------------------------------------
// 9. claim-discipline
// ---------------------------------------------------------------------------

// Required field per classification class. Field names are matched
// case-insensitively as substrings; the semantic role comes from the class
// contract in the specification:
//   checked          an oracle verdict on a stated proposition
//   declared         an authored intent or external assumption with its source
//   observed         an actual observation with a retained evidence path
//   static-possible  a resolved static relation with its derivation or witness
const CLASS_FIELDS = {
  checked: [
    { role: 'oracle', match: (name) => /oracle|provider|engine|checker|compiler/i.test(name) },
    { role: 'proposition', match: (name) => /proposition|claim|verdict|statement|meaning/i.test(name) },
  ],
  declared: [{ role: 'author or authored source', match: (name) => /author|authority|authorship|source|document|declared/i.test(name) }],
  'static-possible': [{ role: 'derivation or witness', match: (name) => /derivation|provider|model|method|basis|scope|witness|raw|evidence|reference/i.test(name) }],
};

async function claimDiscipline(root) {
  const joinedFile = path.join(root, 'joined-result.json');
  const joined = readJson(joinedFile);
  const problems = [];
  const rows = [];

  const existingPaths = (block) => {
    const found = [];
    for (const [name, value] of Object.entries(block)) {
      if (typeof value !== 'string') continue;
      const candidates = path.isAbsolute(value) ? [value] : [path.resolve(root, value)];
      for (const candidate of candidates) {
        if (existsSync(candidate)) found.push({ field: name, path: candidate });
      }
    }
    return found;
  };

  for (const { at, block } of gradedBlocks(joined)) {
    const classification = block.class;
    const names = Object.keys(block);
    const satisfied = [];
    if (classification === 'observed') {
      const paths = existingPaths(block);
      if (paths.length === 0) problems.push(`${at} (class observed): missing an existing evidence path`);
      else satisfied.push(`evidence path via ${paths[0].field}`);
    } else {
      const requirements = CLASS_FIELDS[classification];
      if (requirements === undefined) {
        problems.push(`${at}: unknown class ${JSON.stringify(classification)}`);
        continue;
      }
      for (const requirement of requirements) {
        const hit = names.find((name) => requirement.match(name));
        if (hit === undefined) problems.push(`${at} (class ${classification}): missing ${requirement.role}`);
        else satisfied.push(`${requirement.role} via ${hit}`);
      }
    }
    if (classification === 'static-possible') {
      const hits = [];
      for (const { at: innerAt, text } of collectStrings(block, at)) {
        for (const claim of enforcementClaims(text)) hits.push(`${innerAt}: ${claim}`);
      }
      if (hits.length > 0) problems.push(`${at}: asserts enforcement, authenticity or completion (${hits.slice(0, 3).join(' | ')})`);
      else satisfied.push('no enforcement, authenticity or completion assertion');
    }
    rows.push({ at, class: classification, satisfied });
  }

  // Every runtime observation carries retained per-observation evidence, and
  // its recorded counts recompute from that evidence.
  const runtimeEvidence = [];
  const runtime = Array.isArray(joined.runtime) ? joined.runtime : [];
  const connections = Array.isArray(joined.runtime_connections) ? joined.runtime_connections : [];
  if (runtime.length === 0 && connections.length === 0) problems.push('joined-result.json records no runtime observation');
  const sql = joined.database?.sql;

  runtime.forEach((block, index) => {
    const at = `runtime[${index}]`;
    if (block.class !== 'observed') problems.push(`${at}: class ${block.class} in the runtime observation list`);
    const tracePath = block.sql_trace_path;
    if (typeof tracePath !== 'string' || !existsSync(tracePath)) {
      problems.push(`${at}: sql_trace_path ${JSON.stringify(tracePath)} is not a retained file`);
      return;
    }
    const traceLines = readText(tracePath).split('\n');
    const recomputedCount = traceLines.filter((line) => line.replace(/;\s*$/, '') === sql).length;
    if (recomputedCount !== block.sql_trace_exact_selected_count) {
      problems.push(
        `${at}: sql_trace_exact_selected_count is ${block.sql_trace_exact_selected_count} while ${displayPath(root, tracePath)} holds ${recomputedCount} exact statement lines`,
      );
    }
    const row = {
      at,
      context: block.context ?? null,
      trace: tracePath,
      trace_exact_selected_count: recomputedCount,
      coverage: null,
      digests: [],
    };
    const coveragePath = path.join(path.dirname(tracePath), `${block.context}-view_list-coverage.json`);
    if (existsSync(coveragePath)) {
      const coverage = readJson(coveragePath);
      if (coverage.count !== block.coverage_function_count) {
        problems.push(`${at}: coverage_function_count is ${block.coverage_function_count} while ${displayPath(root, coveragePath)} records ${coverage.count}`);
      }
      const branches = Array.isArray(coverage.branches) ? coverage.branches.slice(0, 2) : null;
      if (JSON.stringify(branches) !== JSON.stringify(block.guard_operand_branches)) {
        problems.push(`${at}: guard_operand_branches differ from the first two rows of ${displayPath(root, coveragePath)}`);
      }
      row.coverage = { path: coveragePath, count: coverage.count, branches_verified: true };
    } else {
      row.coverage = { path: coveragePath, resolved: false };
    }
    for (const [field, candidates] of [
      ['binary_sha256', ['.']],
      ['profile_sha256', ['runtime-connection']],
    ]) {
      const recorded = block[field];
      if (typeof recorded !== 'string') {
        problems.push(`${at}: ${field} is absent`);
        continue;
      }
      const matches = filesByDigest(root, recorded, candidates);
      if (matches.length === 0) problems.push(`${at}: no retained file under the evidence root hashes to ${field} ${recorded}`);
      row.digests.push({ field, resolved_by: matches });
    }
    runtimeEvidence.push(row);
  });

  connections.forEach((block, index) => {
    const at = `runtime_connections[${index}]`;
    if (block.class !== 'observed') problems.push(`${at}: class ${block.class} in the runtime connection list`);
    const paths = existingPaths(block);
    if (paths.length === 0) problems.push(`${at}: no existing evidence path`);
  });

  const ok = problems.length === 0;
  const summary = `${rows.length} graded blocks carry the fields their class requires; ${runtime.length} runtime observations and ${connections.length} connection observations reference retained evidence (trace statements, coverage rows, binary and profile digests recomputed)`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: { blocks: rows, runtime: runtimeEvidence },
  };
}

// ---------------------------------------------------------------------------
// 10. no-enforcement-claim
// ---------------------------------------------------------------------------

async function noEnforcementClaim(root) {
  const joinedFile = path.join(root, 'joined-result.json');
  const joined = readJson(joinedFile);
  const problems = [];
  const hits = [];
  for (const { at, text } of collectStrings(joined)) {
    for (const claim of enforcementClaims(text)) hits.push({ at, claim });
  }
  if (hits.length > 0) {
    for (const hit of hits.slice(0, 12)) problems.push(`${hit.at}: ${hit.claim}`);
    if (hits.length > 12) problems.push(`${hits.length - 12} more assertion clauses`);
  }

  const limits = [
    { at: 'security.relation.limits', values: joined.security?.relation?.limits },
    { at: 'runtime[0].limits', values: joined.runtime?.[0]?.limits },
    { at: 'runtime[1].limits', values: joined.runtime?.[1]?.limits },
  ];
  for (const entry of limits) {
    if (!Array.isArray(entry.values) || entry.values.length === 0) {
      problems.push(`${entry.at} holds no limit entries`);
      continue;
    }
    for (const value of entry.values) {
      if (typeof value !== 'string' || value.trim().length === 0) problems.push(`${entry.at} holds a non-string limit entry`);
    }
  }

  const ok = problems.length === 0;
  const limitReport = limits
    .map((entry) => `${entry.at}: ${Array.isArray(entry.values) ? entry.values.map((value) => JSON.stringify(value)).join('; ') : 'absent'}`)
    .join(' || ');
  const summary = `no string asserts guard enforcement, principal authenticity or effect completion; limits present ${limitReport}`;
  return {
    ok,
    detail: withProblems(summary, problems),
    evidence: {
      limits: limits.map((entry) => ({ at: entry.at, values: entry.values ?? null })),
      assertions: hits,
    },
  };
}

// ---------------------------------------------------------------------------
// entry point
// ---------------------------------------------------------------------------

const CHECKS = [
  ['correspondence-bytes', correspondenceBytes],
  ['manifest-digests', manifestDigests],
  ['compiler-identities', compilerIdentities],
  ['catalog-provenance', catalogProvenance],
  ['guard-span', guardSpan],
  ['relation-recompute', relationRecompute],
  ['same-handler-families', sameHandlerFamilies],
  ['database-join', databaseJoin],
  ['claim-discipline', claimDiscipline],
  ['no-enforcement-claim', noEnforcementClaim],
];

export async function verifyAuthentic(evidenceRoot = DEFAULT_EVIDENCE_ROOT, options = {}) {
  if (typeof evidenceRoot !== 'string' || evidenceRoot.length === 0) {
    throw new Error('verifyAuthentic requires an evidence root path');
  }
  const root = path.resolve(evidenceRoot);
  if (!existsSync(root)) throw new Error(`evidence root is absent: ${root}`);
  const selected = Array.isArray(options.checks) && options.checks.length > 0 ? new Set(options.checks) : null;
  const checks = [];
  for (const [id, run] of CHECKS) {
    if (selected !== null && !selected.has(id)) continue;
    try {
      const outcome = await run(root, options);
      checks.push({ id, ok: outcome.ok === true, detail: String(outcome.detail ?? ''), evidence: outcome.evidence ?? null });
    } catch (error) {
      checks.push({ id, ok: false, detail: `check did not complete: ${error instanceof Error ? error.message : String(error)}`, evidence: null });
    }
  }
  return { checks, ok: checks.every((entry) => entry.ok) };
}

function invokedDirectly() {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}

if (invokedDirectly()) {
  const root = process.argv[2] ?? DEFAULT_EVIDENCE_ROOT;
  verifyAuthentic(root)
    .then((result) => {
      process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
      process.exitCode = result.ok ? 0 : 1;
    })
    .catch((error) => {
      process.stderr.write(`verification did not run: ${error instanceof Error ? error.stack : String(error)}\n`);
      process.exitCode = 2;
    });
}
