// Issue #261: the ONE derivation module for the surface-truth pins the test suite imports
// instead of hand-typed literals. Every export derives from the same src tables the surfaces
// serve, so a surface change lands here by construction — never as a stale literal in a test.
//
//   commandKeys()             — the byte-stable insertion-order key list of APPLICATION_COMMAND_DEFINITIONS
//   swarmVerbs()              — the ten docs/39 swarm verbs, in contract (table-spread) order
//   applicationCardCommands() — the real `application.card().commands` derivation (table keys,
//                               then the M4b canonical-grammar names advertised beside them)
//   mockApplicationCard(id)   — a mock application card for tests, commands derived from the table
//   webCardCommands()         — the sorted web-admitted card names plus the six wave direct ports
//   ordinaryMcpToolNames()    — the SHIPPED ordinary MCP surface in SERVED order (the core table)
//   northboundApplicationToolNames() — the RAW McpFleetServer application table in SERVED order
//   combinedMcpToolNames()    — the combined MCP surface names (sorted, the served set)
//
// (impl/scripts/surface-inventory-artifact.json, regenerated by buildSurfaceInventoryArtifact
// in surface-conformance.mjs through `node impl/scripts/surface-gate.mjs --write`), not against
// literals retyped here.
import { readFileSync } from 'node:fs';
import { APPLICATION_COMMAND_DEFINITIONS } from '../src/application.mjs';
import { APPLICATION_SEMANTIC_REGISTRY } from '../src/application-semantics.mjs';
import { SWARM_COMMAND_NAMES } from '../src/swarm-contract.mjs';
import { CORE_TOOL_NAMES } from '../src/mcp-core-tools.mjs';
import { mcpCombinedToolNames, McpFleetServer } from '../src/mcp-northbound.mjs';

/** The byte-stable insertion-order key list of APPLICATION_COMMAND_DEFINITIONS (docs/36 §9 M3:
 * the swarm verbs lead, then the legacy set — a reorder, drop, or addition of a table row moves
 * this list). Fresh array each call; callers must not mutate the table through it. */
export function commandKeys() {
  return [...Object.keys(APPLICATION_COMMAND_DEFINITIONS)];
}

/** The ten docs/39 swarm verbs in contract order — the ONE source is SWARM_COMMAND_NAMES; the
 * application table spreads it first, so the table's swarm block and this list cannot drift. */
export function swarmVerbs() {
  return [...SWARM_COMMAND_NAMES];
}

/** docs/36 §9 M4b: the canonical grammar names advertised beside the retained legacy commands on
 * `card().commands` — every ordinary canonical operation whose legacy application-command spelling
 * is a live table entry. Derives from registry v2 exactly like CANONICAL_CARD_COMMANDS in
 * application.mjs (the card's own assembly), so the card and this list cannot drift. */
function canonicalCardCommands() {
  const byKey = new Map(APPLICATION_SEMANTIC_REGISTRY.canonicalOperations.map((op) => [op.key, op]));
  const seen = new Set();
  const commands = [];
  for (const alias of APPLICATION_SEMANTIC_REGISTRY.surfaceAliases) {
    if (alias.surface !== 'application.commands') continue;
    if (!Object.hasOwn(APPLICATION_COMMAND_DEFINITIONS, alias.name)) continue;
    const operation = byKey.get(alias.canonical);
    if (!operation || operation.profile !== 'ordinary' || seen.has(alias.canonical)) continue;
    seen.add(alias.canonical);
    commands.push(alias.canonical);
  }
  return commands;
}

/** The real card's command list: table keys in insertion order, then the M4b canonical names. */
export function applicationCardCommands() {
  return [...commandKeys(), ...canonicalCardCommands()];
}

/** A mock application card whose commands derive from the command table (the real card's
 * derivation, not a retyped list). Satisfies every surface's card validation: the McpFleetServer
 * constructor requires the served entries to be a subset, and the web bus re-derives its served
 * command list from its own admission entries. */
export function mockApplicationCard(repoId) {
  return { schemaVersion: 1, repoId, commands: applicationCardCommands() };
}

// The six wave direct-port verbs (contract-fold v1.1 D2 / G3): admitted on the web bus WITHOUT a
// table entry — the same six surface-conformance.mjs (WAVE_DIRECT_PORT_VERBS) and the web bus's
// wave entries name.
const WAVE_DIRECT_PORT_VERBS = Object.freeze([
  'waves.list', 'waves.progress', 'waves.run', 'waves.send', 'waves.start', 'waves.stop',
]);

/** The web-admitted card projection, sorted: the table's web-admitted command names plus the six
 * wave direct ports — today's web.bus profile (41 names), byte-stable against the committed
 * artifact's `profiles['web.bus']`. The #99/#179 accessor pair rides the web bus WITHOUT being
 * carded (registry-operation direct ports — see the R7 third arm, #566). */
export function webCardCommands() {
  return [
    ...commandKeys().filter((name) => APPLICATION_COMMAND_DEFINITIONS[name].web),
    ...WAVE_DIRECT_PORT_VERBS,
  ].sort();
}

const SURFACE_TRUTH_REPO_ID = 'repo-surface-truth';
function surfaceTruthServer(surface) {
  const coordination = Object.fromEntries(
    ['admitMcpCall', 'completeMcpCall', 'failMcpCall', 'mcpCall', 'recordMcpAudit']
      .map((method) => [method, async () => ({})]),
  );
  const principal = {
    userId: 'surface-truth', sessionId: 'surface-truth',
    capabilities: ['observe', 'control', 'approve', 'emergency_stop'],
    repoIds: [SURFACE_TRUTH_REPO_ID], expiresAt: new Date(8640000000000000).toISOString(), revoked: false,
  };
  const application = {
    repoId: SURFACE_TRUTH_REPO_ID,
    card: () => mockApplicationCard(SURFACE_TRUTH_REPO_ID),
    async command() { return {}; },
    async authorizeReplay() { return true; },
  };
  return new McpFleetServer({
    coordinator: {}, coordination, principal, repoIds: [SURFACE_TRUTH_REPO_ID],
    surface, application, applicationOwned: false,
  });
}

/** The shipped ordinary MCP surface's tool names in SERVED order — the seven verb-tools, one per
 * family, that the production wrapper advertises on `surface: 'application'` (docs/49 §2 law (a),
 * MCP.md "One tool table, two entries"). The ONE source is CORE_TOOL_NAMES: surface-conformance.mjs
 * records that same table in the committed artifact's `profiles['mcp.application']`, so the shipped
 * surface and the profile cannot drift. */
export function ordinaryMcpToolNames() {
  return [...CORE_TOOL_NAMES];
}

/** The RAW `McpFleetServer` application table's tool names in SERVED order — the flat
 * `baton_<noun>_<verb>` list an embedder that constructs the server directly is served (docs/49 §2:
 * the raw class keeps its flat table for embedders and its own pins). The shipped composition
 * replaces that table with the core one above, so the phase pins that read the raw wire surface
 * derive from it. The order is the definition order of the table mcp-northbound.mjs assembles — the
 * one honest derivation reads it off a real server. The stub below satisfies the constructor's
 * authority checks only; no dispatch ever runs. */
export function northboundApplicationToolNames() {
  return surfaceTruthServer('application').toolDefinitions.map((tool) => tool.name);
}

/** The combined MCP surface's tool names (sorted — the served set, byte-stable against the
 * committed artifact's `profiles['mcp.combined']`), derived through mcp-northbound's own
 * mcpCombinedToolNames(). */
export function combinedMcpToolNames() {
  return mcpCombinedToolNames();
}

// The committed byte-stability witness for the command-key list: the `commandKeys` leg of the
// inventory artifact (impl/scripts/surface-inventory-artifact.json), regenerated by
// `node impl/scripts/surface-gate.mjs --write` and checked by the gate — so a reorder, drop, or
// addition of a table row is a reviewed artifact diff, never a literal retyped into a test.
// Issue #582: the committed byte-stability witness is gone with the banned census file. The
// command-key list derives live from APPLICATION_COMMAND_DEFINITIONS — the same table the
// artifact's commandKeys leg was built from.
export const BYTE_STABLE_COMMAND_KEYS = Object.freeze(commandKeys());
