#!/usr/bin/env node

// Issue #43: mechanical control-surface inventory. Emits (as markdown) the current truth of
// every agent-facing control surface so the unified-grammar work (docs/35) audits against
// facts, not memory, and drift after future changes is one command away:
//
//   node impl/scripts/surface-audit.mjs
//
// Sources: the semantic registry and application command table are imported (exact); MCP tool
// names, CLI verb rows, embedded class methods, and phase literals are extracted textually
// (best-effort, labeled as such). This tool is read-only and asserts nothing — the conformance
// contracts that will pin surfaces to the registry arrive with the docs/35 migration phases.

import { readFileSync } from 'node:fs';

import { APPLICATION_SEMANTIC_REGISTRY } from '../src/application-semantics.mjs';
import { APPLICATION_COMMAND_DEFINITIONS } from '../src/application.mjs';

const src = (name) => readFileSync(new URL(`../src/${name}`, import.meta.url), 'utf8');

function extractAll(text, pattern) {
  const found = new Set();
  for (const match of text.matchAll(pattern)) found.add(match[1] ?? match[0]);
  return [...found].sort();
}

export function collectSurfaceInventory() {
  const registry = APPLICATION_SEMANTIC_REGISTRY;
  const definitions = Object.keys(APPLICATION_COMMAND_DEFINITIONS);
  const webCommands = definitions
    .filter((name) => APPLICATION_COMMAND_DEFINITIONS[name].web)
    .map((name) => name.replaceAll('.', '_'));
  const mcpNames = extractAll(src('mcp-northbound.mjs'), /'((?:fleet|baton)_[a-z0-9_]+)'/gu);
  const clientText = src('application-client.mjs');
  const embedded = [];
  {
    let currentClass = null;
    for (const line of clientText.split('\n')) {
      const classMatch = /^(?:export )?class (\w+)/u.exec(line);
      if (classMatch) { currentClass = classMatch[1]; continue; }
      const methodMatch = /^ {2}(?:async |static )?\*?([a-zA-Z][a-zA-Z0-9_]*)\(/u.exec(line);
      if (currentClass && methodMatch && methodMatch[1] !== 'constructor') {
        embedded.push(`${currentClass}.${methodMatch[1]}`);
      }
    }
  }
  const phaseLiterals = new Set([
    ...extractAll(src('application.mjs'), /phase = '([a-z_]+)'/gu),
    ...extractAll(src('wave.mjs'), /'(work_completed|start_failed)'/gu),
    ...extractAll(src('application-cli.mjs'), /TERMINAL_RUN_PHASES = new Set\(\[([^\]]+)\]/gu)
      .flatMap((body) => [...body.matchAll(/'([a-z_]+)'/gu)].map((m) => m[1])),
  ]);
  const synonymDensity = {};
  const applicationLayer = ['application.mjs', 'application-client.mjs', 'application-cli.mjs',
    'application-semantics.mjs', 'application-deployment.mjs'].map(src).join('\n');
  for (const word of ['worker', 'member', 'workstream', 'seat', 'assignee']) {
    synonymDensity[word] = (applicationLayer.match(new RegExp(word, 'giu')) ?? []).length;
  }
  return Object.freeze({
    registryOperations: Object.keys(registry.operations),
    registryActions: Object.keys(registry.actions),
    commandDefinitions: definitions,
    webCommands,
    cliCommands: registry.cli.commands.map((command) => ({
      id: command.id, subcommand: command.subcommand ?? null,
      action: command.action ?? null, usage: command.usage ?? null,
    })),
    mcpFleetTools: mcpNames.filter((name) => name.startsWith('fleet_')),
    mcpBatonTools: mcpNames.filter((name) => name.startsWith('baton_')),
    embeddedMethods: [...new Set(embedded)].sort(),
    phaseLiterals: [...phaseLiterals].sort(),
    synonymDensity,
  });
}

export function renderSurfaceAudit(inventory = collectSurfaceInventory()) {
  const section = (title, rows) => `### ${title} (${rows.length})\n\n${rows.map((row) => `- \`${row}\``).join('\n')}\n`;
  const lines = [
    '## Surface inventory (generated by impl/scripts/surface-audit.mjs)', '',
    section('Semantic registry operations', inventory.registryOperations),
    section('Semantic registry actions (run.do targets)', inventory.registryActions),
    section('Application command definitions (older authoritative table)', inventory.commandDefinitions),
    section('Web bus command names (derived: definitions with web flag, dots to underscores)', inventory.webCommands),
    `### CLI verb rows (${inventory.cliCommands.length})\n\n${inventory.cliCommands
      .map((row) => `- \`${row.usage ?? row.id}\`${row.action ? ` → action \`${row.action}\`` : ''}`).join('\n')}\n`,
    section('MCP fleet_* dialect (textual extraction)', inventory.mcpFleetTools),
    section('MCP baton_* dialect (textual extraction)', inventory.mcpBatonTools),
    section('Embedded client methods (textual extraction)', inventory.embeddedMethods),
    section('Run phase string literals across surfaces', inventory.phaseLiterals),
    `### Synonym density for the delegated-seat concept (application layer)\n\n${Object.entries(inventory.synonymDensity)
      .map(([word, count]) => `- ${word}: ${count}`).join('\n')}\n`,
  ];
  return lines.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.stdout.write(`${renderSurfaceAudit()}\n`);
}
