import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import { McpFleetServer, WebNorthbound, createDriver } from '../src/index.mjs';

const canonical = (value) => Array.isArray(value) ? value.map(canonical) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])])) : value;
const sha = (value) => createHash('sha256').update(Buffer.isBuffer(value) ? value : JSON.stringify(canonical(value))).digest('hex');
const coordinate = Object.freeze({ ecosystem: 'npm', package: '@scope/provider-green', version: '1.2.3' }); const fingerprint = sha(Buffer.from('provider-green-key')); const fingerprintTwo = sha(Buffer.from('provider-green-key-two')); const indexEpoch = 'a'.repeat(64); const atlasCardDigest = 'b'.repeat(64);
const policyProjection = Object.freeze({ licenseAllow: ['MIT'], licenseDeny: [], minScorecard: null, requireProviderVerifiedProvenance: false, blockDeprecated: true, ttlMs: 60_000 }); const policyHash = sha(policyProjection);
const reconcileLimits = { maxDecisionTargets: 100, maxGuardTargets: 100, maxAffectedReads: 100, maxStateRows: 1000, maxObservedPolicyHashes: 16, maxEventBytes: 256 * 1024 };

function feedSource(providerId = 'fixture.green', keyFingerprint = fingerprint, state = {}) { return { card: () => ({ schemaVersion: 1, providerId, adapterId: `${providerId}-v1`, version: '1', modes: ['poll', 'webhook'], ecosystem: 'npm', semantics: 'authenticated_hint', auth: { scheme: 'injected-test', keyFingerprints: [keyFingerprint] }, ceilings: { maxDeliveryBytes: 4096, maxCoordinates: 4, maxAdvisoryIds: 8, maxIdentityBytes: 256 }, poll: { origin: 'https://fixture.invalid', operation: `/v1/${providerId}/full`, cursorKind: 'sequence', initialSequence: 1, redirects: 'deny', maxPages: 2, maxItems: 8, maxPageBytes: 4096, maxTotalBytes: 16384, maxWallMs: 1000, maxBackoffMs: 1000, maxClockSkewMs: 300_000 } }),
  async verifyDelivery({ raw }) { const parsed = JSON.parse(raw); const digest = sha(raw); return { schemaVersion: 1, providerId, deliveryId: parsed.deliveryId, rawDigest: digest, rawBytes: raw.length, authReceiptDigest: sha(Buffer.from(`auth:${providerId}:${parsed.deliveryId}`)), keyFingerprint, occurredAt: parsed.occurredAt, sequence: parsed.sequence, coordinates: parsed.coordinates, advisoryIds: [], source: { handle: `art:sha256:${digest}`, digest, bytes: raw.length, mediaType: 'application/json' } }; }, async pollFull({ signal } = {}) { state.pollCalls = (state.pollCalls ?? 0) + 1; state.pollActive = (state.pollActive ?? 0) + 1; state.maxPollActive = Math.max(state.maxPollActive ?? 0, state.pollActive); try { if (state.blockPoll === providerId) return await new Promise((resolve, reject) => { state.releasePoll = () => resolve(state.polls?.[providerId]); signal.addEventListener('abort', () => { state.pollAborted = (state.pollAborted ?? 0) + 1; if (state.resolvePollOnAbort) resolve(state.polls?.[providerId]); else reject(Object.assign(new Error('cancelled'), { code: 'cancelled' })); }, { once: true }); }); return state.polls?.[providerId]; } finally { state.pollActive -= 1; } }, reverifyPollSync(proof) { return proof; } }; }

function quartermaster(state) {
  const vetPolicy = state.policyProjection; const vetPolicyHash = sha(vetPolicy);
  const isAdverse = (value) => state.adverse || state.adversePackages.has(value.package);
  const snapshotFor = (value) => ({ identity: { ...value, ...(state.identityExtra ?? {}) }, recommendation: isAdverse(value) ? 'block' : 'borrow_candidate', policyHash: vetPolicyHash, policy: { hash: vetPolicyHash, license: 'allow', blocked: isAdverse(value) ? ['known_vulnerability'] : [], unknown: [] }, factDigest: sha({ coordinate: value, adverse: isAdverse(value), policyHash: vetPolicyHash }), asOf: '2026-07-13T06:00:00.000Z', expiresAt: '2026-07-13T06:01:00.000Z', indexEpoch, overlayDigest: 'c'.repeat(64) });
  return { vetPolicy, vetPolicyHash,
    card: () => ({ name: 'cartographer-quartermaster', version: 'fixture', underlying: ['fixture'], ops: { 'reuse.vet': { latency_class: 'bounded_batch', deterministic: false, side_effects: [], reverifiable: 'fresh_observation' } }, reusePolicy: { schemaVersion: 1, policyId: 'quartermaster-vet-policy-v1', hash: vetPolicyHash, projection: vetPolicy } }),
    async invoke(op, args) { assert.equal(op, 'reuse.vet'); state.invokes += 1; const identity = { ecosystem: args.ecosystem, package: args.package, version: args.version }; const snapshot = snapshotFor(identity); const adverse = isAdverse(identity); const dossier = { ...snapshot, advisories: adverse ? [{ id: 'OSV-adverse', malicious: false }] : [], advisoryIds: adverse ? ['OSV-adverse'] : [] }; const digest = sha(dossier); return { op, status: 'ok', summary: 'fixture official observation', payload: [dossier], refs: [{ kind: 'dependency-dossier', mediaType: 'application/vnd.baton.dependency-dossier+json', handle: `art:sha256:${digest}`, digest, bytes: 100 }], cost: { tokens_out: 10, wall_ms: 1, usd: 0, underlying: 'fixture' }, provenance: { mergeAuthority: false, verificationAuthority: false } }; },
    async reverify(claim, op, args) { state.reverifies += 1; const identity = { ecosystem: args.ecosystem, package: args.package, version: args.version }; return { ok: true, observedDigest: claim.refs[0].digest, snapshot: snapshotFor(identity) }; } };
}

async function world(overrides = {}) {
  const root = mkdtempSync(join(tmpdir(), 'baton-provider-reconcile-')); const repoRoot = join(root, 'repo'); mkdirSync(repoRoot); execFileSync('git', ['init', '-q'], { cwd: repoRoot }); const logDir = join(root, 'log'); const state = { invokes: 0, reverifies: 0, adverse: overrides.adverse ?? false, adversePackages: new Set(overrides.adversePackages ?? []), identityExtra: overrides.identityExtra ?? null, policyProjection, polls: {}, pollCalls: 0, currentCalls: 0 };
  const authority = { card: () => ({ schemaVersion: 1, authorityId: 'fixture-index-authority', repoId: 'repo-a', atlasCardDigest }), async current() { state.currentCalls += 1; return { schemaVersion: 1, repoId: 'repo-a', treeSha: state.currentCalls > 1 && overrides.changeIndex ? 'ffff' : 'abcd', indexEpoch, atlasCardDigest }; }, async reverify() { return { ok: true }; } };
  const options = { repoRoot, repoId: 'repo-a', logDir, adapters: {}, now: () => Date.parse('2026-07-13T06:00:01.000Z'), advisoryFeedSources: { 'fixture.green': feedSource('fixture.green', fingerprint, state), 'fixture.green-two': feedSource('fixture.green-two', fingerprintTwo, state) }, capabilities: { 'cartographer-quartermaster': quartermaster(state) }, maxCapabilityBudgetTokens: 10_000, maxCapabilityEnvelopeBytes: 256 * 1024,
    reuseDecisionPolicy: { authorize: async () => true, authorizeRecheck: async () => true, maxNeedBytes: 2048, maxRationaleBytes: 8192, policyReconcile: reconcileLimits }, providerReconciliation: { budgetTokens: 10_000, indexAuthority: authority } };
  if (overrides.providerPolling) options.providerPolling = overrides.providerPolling;
  if (overrides.providerRead) options.providerRead = overrides.providerRead;
  if (overrides.blockPoll) state.blockPoll = overrides.blockPoll;
  if (overrides.resolvePollOnAbort) state.resolvePollOnAbort = true;
  const driver = createDriver(options); const raw = Buffer.from(JSON.stringify({ deliveryId: 'delivery-green', occurredAt: '2026-07-13T06:00:00.000Z', sequence: 1, coordinates: overrides.coordinates ?? [coordinate] })); const admitted = await driver.coordinator.receiveProviderDelivery('fixture.green', { mode: 'webhook', raw });
  return { driver, options, state, admitted };
}

async function until(fn, timeoutMs = 2000) { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { const value = fn(); if (value) return value; await new Promise((resolve) => setTimeout(resolve, 5)); } throw new Error('timed out waiting for provider poll lifecycle'); }

test('AF3/AF4/AF8/AF9: seedless official green refresh atomically resolves pending and creates only verified Source lineage', async () => {
  const w = await world(); const before = w.driver.coordination.snapshot(); const result = await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id);
  assert.equal(result.result, 'ignored_non_adverse'); assert.equal(result.processing.status, 'ignored_non_adverse'); assert.equal(w.driver.coordination.pendingProviderReconciliation('repo-a', coordinate).length, 0);
  assert.equal(w.driver.coordination.snapshot().reuseRiskGuards.length, 0); assert.equal(w.driver.coordination.snapshot().knowledge.nodes.filter((node) => node.type === 'Finding').length, before.knowledge.nodes.filter((node) => node.type === 'Finding').length);
  const official = w.driver.coordination.snapshot().knowledge.nodes.find((node) => node.promotion?.trigger === 'provider.official'); assert.equal(official.type, 'Source'); assert.equal(official.grounding, 'verified'); assert.ok(w.driver.coordination.snapshot().knowledge.edges.some((edge) => edge.type === 'DerivedFrom' && edge.from === official.id && edge.to === w.admitted.receipt.nodeId));
  const counts = { invokes: w.state.invokes, reverifies: w.state.reverifies }; const retry = await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id); assert.equal(retry.result, 'idempotent'); assert.deepEqual({ invokes: w.state.invokes, reverifies: w.state.reverifies }, counts); w.driver.close();
  const replay = createDriver(w.options); assert.equal(replay.coordination.providerProcessing(w.admitted.processing.id).status, 'ignored_non_adverse'); assert.equal(replay.coordination.pendingProviderReconciliation('repo-a', coordinate).length, 0); replay.close();
});

test('AF3/AF6: multi-coordinate green processing completes as one root and exposes no pending prefix', async () => {
  const second = { ecosystem: 'npm', package: '@scope/provider-green-two', version: '2.0.0' }; const key = (value) => `${value.ecosystem}\0${value.package}\0${value.version}`; const coordinates = [coordinate, second].sort((a, b) => key(a) < key(b) ? -1 : key(a) > key(b) ? 1 : 0); const w = await world({ coordinates });
  const result = await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id); assert.equal(result.processing.observations.length, 2); assert.equal(w.state.invokes, 2); assert.equal(w.state.reverifies, 2);
  assert.equal(coordinates.every((value) => w.driver.coordination.pendingProviderReconciliation('repo-a', value).length === 0), true); assert.equal(w.driver.coordination.events().filter((event) => event.kind === 'provider.processing_checked').length, 1); w.driver.close();
});

test('AF4/AF6: index change leaves the complete processing root pending and unfenced from false green', async () => {
  const w = await world({ changeIndex: true }); await assert.rejects(w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id), (error) => error.code === 'provider_index_changed'); assert.equal(w.driver.coordination.providerProcessing(w.admitted.processing.id).status, 'pending'); assert.equal(w.driver.coordination.pendingProviderReconciliation('repo-a', coordinate).length, 1); assert.equal(w.driver.coordination.events().some((event) => ['provider.processing_checked', 'knowledge.reuse_provider_guarded'].includes(event.kind)), false, 'audit evidence may append, but no completion or guard may partially append'); w.driver.close();
});

test('PF3-PF5: Coordinator full poll durably dedupes receipts then performs the sole health recovery CAS', async () => {
  const w = await world(); const raw = (deliveryId, sequence) => Buffer.from(JSON.stringify({ deliveryId, occurredAt: '2026-07-13T06:00:00.000Z', sequence, coordinates: [coordinate] })); await w.driver.coordinator.receiveProviderDelivery('fixture.green', { mode: 'webhook', raw: raw('delivery-3', 3) }); const epoch = w.admitted.receipt.sourceEpoch; assert.equal(w.driver.coordination.providerSourceHealth('repo-a', 'fixture.green', epoch).status, 'reconciliation_required');
  const items = [raw('delivery-green', 1), raw('delivery-2', 2), raw('delivery-3', 3)]; w.state.polls['fixture.green'] = { schemaVersion: 1, providerId: 'fixture.green', pollId: 'full-window-1', observedAt: '2026-07-13T06:00:00.000Z', window: { fromSequence: 1, toSequence: 3 }, finalSequence: 3, cursorDigest: sha('cursor-3'), authReceiptDigest: sha('poll-auth'), keyFingerprint: fingerprint, pages: [{ raw: Buffer.from('{"page":1}'), items }] };
  const result = await w.driver.coordinator.reconcileProviderSource('fixture.green'); assert.equal(result.result, 'healthy'); assert.equal(result.receipts.length, 3); assert.equal(w.driver.coordination.providerSourceHealth('repo-a', 'fixture.green', epoch).status, 'healthy'); assert.equal(w.driver.coordination.events().filter((event) => event.kind === 'provider.reconciliation_completed').length, 1);
  const calls = w.state.pollCalls; assert.equal((await w.driver.coordinator.reconcileProviderSource('fixture.green')).result, 'not_required'); assert.equal(w.state.pollCalls, calls, 'healthy source does not spend a network poll'); await w.driver.coordinator.receiveProviderDelivery('fixture.green', { mode: 'webhook', raw: raw('delivery-5', 5) }); assert.equal(w.driver.coordination.providerSourceHealth('repo-a', 'fixture.green', epoch).status, 'reconciliation_required'); w.driver.close();
});

test('PF6: createDriver automatically recovers one degraded source and records sanitized lifecycle', async () => {
  const w = await world({ providerPolling: { intervalMs: 20, initialBackoffMs: 10 } }); const raw = (deliveryId, sequence) => Buffer.from(JSON.stringify({ deliveryId, occurredAt: '2026-07-13T06:00:00.000Z', sequence, coordinates: [coordinate] }));
  await w.driver.coordinator.receiveProviderDelivery('fixture.green', { mode: 'webhook', raw: raw('delivery-3', 3) }); const epoch = w.admitted.receipt.sourceEpoch;
  const items = [raw('delivery-green', 1), raw('delivery-2', 2), raw('delivery-3', 3)]; w.state.polls['fixture.green'] = { schemaVersion: 1, providerId: 'fixture.green', pollId: 'automatic-window-1', observedAt: '2026-07-13T06:00:00.000Z', window: { fromSequence: 1, toSequence: 3 }, finalSequence: 3, cursorDigest: sha('automatic-cursor-3'), authReceiptDigest: sha('automatic-poll-auth'), keyFingerprint: fingerprint, pages: [{ raw: Buffer.from('{"page":1}'), items }] };
  await until(() => w.driver.coordination.providerSourceHealth('repo-a', 'fixture.green', epoch)?.status === 'healthy');
  assert.equal(w.state.maxPollActive, 1); assert.ok(w.driver.providerPoller.status().find((row) => row.providerId === 'fixture.green').attempts >= 1);
  const lifecycle = w.driver.log.read('hub-provider-poller'); assert.ok(lifecycle.some((event) => event.kind === 'provider.poll_completed' && event.payload.providerId === 'fixture.green')); assert.equal(JSON.stringify(lifecycle).includes('cursor'), false);
  assert.throws(() => createDriver(w.options), (error) => error.code === 'coordination_writer_busy');
  assert.throws(() => w.driver.close(), (error) => error.code === 'driver_async_close_required'); assert.equal(await w.driver.closeAsync(), true); assert.equal(await w.driver.closeAsync(), false);
});

test('PF6: closeAsync aborts and awaits even a hostile abort-resolving poll before fencing coordinator and writer lease', async () => {
  const w = await world({ providerPolling: { intervalMs: 20, initialBackoffMs: 10 }, blockPoll: 'fixture.green', resolvePollOnAbort: true }); const raw = (deliveryId, sequence) => Buffer.from(JSON.stringify({ deliveryId, occurredAt: '2026-07-13T06:00:00.000Z', sequence, coordinates: [coordinate] }));
  await w.driver.coordinator.receiveProviderDelivery('fixture.green', { mode: 'webhook', raw: raw('delivery-3', 3) }); const epoch = w.admitted.receipt.sourceEpoch;
  const items = [raw('delivery-green', 1), raw('delivery-2', 2), raw('delivery-3', 3)]; w.state.polls['fixture.green'] = { schemaVersion: 1, providerId: 'fixture.green', pollId: 'hostile-abort-window', observedAt: '2026-07-13T06:00:00.000Z', window: { fromSequence: 1, toSequence: 3 }, finalSequence: 3, cursorDigest: sha('hostile-abort-cursor'), authReceiptDigest: sha('hostile-abort-auth'), keyFingerprint: fingerprint, pages: [{ raw: Buffer.from('{"page":1}'), items }] };
  await until(() => w.driver.providerPoller.status().find((row) => row.providerId === 'fixture.green')?.active === true);
  const before = w.driver.coordination.snapshot().lastSeq; assert.throws(() => w.driver.close(), (error) => error.code === 'driver_async_close_required'); assert.equal(w.driver.coordination.providerSourceHealth('repo-a', 'fixture.green', epoch).status, 'reconciliation_required');
  assert.equal(await w.driver.closeAsync(), true); assert.equal(w.state.pollAborted, 1); assert.equal(w.driver.providerPoller.status().some((row) => row.active || row.scheduled), false); assert.equal(w.driver.coordination._writerLease, null); assert.equal(w.driver.coordination.snapshot().lastSeq, before); assert.equal(w.driver.coordination.events().some((event) => event.kind === 'provider.reconciliation_completed'), false);
  assert.throws(() => w.driver.coordinator.tick(), (error) => error.code === 'coordinator_closed');
  const late = await w.driver.advisoryFeeds.verify('fixture.green', { mode: 'webhook', raw: raw('delivery-late', 4) }); assert.throws(() => w.driver.coordination.recordProviderDelivery({ repoId: 'repo-a', receipt: late }, { actor: 'provider:fixture.green', key: 'provider:late-after-close' }), (error) => error.code === 'coordination_writer_lost'); assert.equal(w.driver.coordination.snapshot().lastSeq, before);
});

test('PF6: writer-lease loss during fetch leaves health degraded and prevents every late append', async () => {
  const w = await world({ providerPolling: { intervalMs: 20, initialBackoffMs: 10 }, blockPoll: 'fixture.green' }); const raw = (deliveryId, sequence) => Buffer.from(JSON.stringify({ deliveryId, occurredAt: '2026-07-13T06:00:00.000Z', sequence, coordinates: [coordinate] }));
  await w.driver.coordinator.receiveProviderDelivery('fixture.green', { mode: 'webhook', raw: raw('delivery-3', 3) }); const epoch = w.admitted.receipt.sourceEpoch;
  const items = [raw('delivery-green', 1), raw('delivery-2', 2), raw('delivery-3', 3)]; w.state.polls['fixture.green'] = { schemaVersion: 1, providerId: 'fixture.green', pollId: 'lost-lease-window', observedAt: '2026-07-13T06:00:00.000Z', window: { fromSequence: 1, toSequence: 3 }, finalSequence: 3, cursorDigest: sha('lost-lease-cursor'), authReceiptDigest: sha('lost-lease-auth'), keyFingerprint: fingerprint, pages: [{ raw: Buffer.from('{"page":1}'), items }] };
  await until(() => w.driver.providerPoller.status().find((row) => row.providerId === 'fixture.green')?.active === true); const before = w.driver.coordination.snapshot().lastSeq;
  assert.equal(w.driver.coordination.releaseWriterLease(), true); w.state.releasePoll();
  await until(() => w.driver.providerPoller.status().find((row) => row.providerId === 'fixture.green')?.lastErrorCode === 'coordination_writer_lost');
  assert.equal(w.driver.coordination.snapshot().lastSeq, before); assert.equal(w.driver.coordination.providerSourceHealth('repo-a', 'fixture.green', epoch).status, 'reconciliation_required'); assert.equal(w.driver.coordination.events().some((event) => event.kind === 'provider.reconciliation_completed'), false);
  assert.equal(await w.driver.closeAsync(), true); assert.throws(() => w.driver.coordinator.tick(), (error) => error.code === 'coordinator_closed');
});

test('PF7: direct, web, and MCP provider status reads are scoped, bounded, and secret-free', async () => {
  const w = await world({ providerRead: { maxProviders: 4, maxProcessing: 4, maxStateRows: 32, maxBytes: 8192 } });
  const direct = w.driver.coordinator.readProviderStatus({}, { repoId: 'repo-a' }); assert.equal(direct.currentProcessing.length, 1); assert.equal(direct.historicalProcessing.length, 0); assert.equal(direct.providers.length, 1);
  await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id); const completed = w.driver.coordinator.readProviderStatus({ limit: 1 }, { repoId: 'repo-a' }); assert.equal(completed.currentProcessing.length, 0); assert.equal(completed.historicalProcessing.length, 1);
  const encoded = JSON.stringify(completed); for (const forbidden of ['fixture.invalid', fingerprint, 'authReceiptDigest', 'keyFingerprint', 'cursorValue', 'privateCas', 'rawDigest']) assert.equal(encoded.includes(forbidden), false, forbidden); assert.match(completed.providers[0].cursorDigest ?? '', /^(?:|[a-f0-9]{64})$/);
  assert.throws(() => w.driver.coordinator.readProviderStatus({}, { repoId: 'repo-b' }), (error) => error.code === 'reuse_repo_mismatch'); assert.throws(() => w.driver.coordinator.readProviderStatus({ limit: 5 }, { repoId: 'repo-a' }), (error) => error.code === 'provider_read_invalid'); assert.throws(() => w.driver.coordinator.readProviderStatus({ providerId: 'unknown.provider' }, { repoId: 'repo-a' }), (error) => error.code === 'provider_read_invalid');

  const principal = { userId: 'observer', sessionId: 'session-1', credentialId: 'credential-1', authMethod: 'bearer', expiresAt: '2099-01-01T00:00:00.000Z', revoked: false, capabilities: ['observe'], repoIds: ['repo-a'] };
  const web = new WebNorthbound({ coordinator: w.driver.coordinator, coordination: w.driver.coordination, allowedOrigins: ['https://control.test'], repoIds: ['repo-a'], now: () => Date.parse('2026-07-13T06:00:01.000Z') });
  const webResult = await web.execute({ transport: 'https', origin: 'https://control.test', principal }, { schemaVersion: 1, commandId: 'provider-status-1', idempotencyKey: 'provider-status-1', command: 'provider_status', args: { limit: 1 }, repoId: 'repo-a', origin: 'https://control.test' }); assert.equal(webResult.status, 200); assert.deepEqual(webResult.body.result.providers, completed.providers); assert.deepEqual(webResult.body.result.historicalProcessing, completed.historicalProcessing);
  const refusedWeb = await web.execute({ transport: 'https', origin: 'https://control.test', principal: { ...principal, capabilities: ['control'] } }, { schemaVersion: 1, commandId: 'provider-status-2', idempotencyKey: 'provider-status-2', command: 'provider_status', args: {}, repoId: 'repo-a', origin: 'https://control.test' }); assert.equal(refusedWeb.status, 403);

  const mcp = new McpFleetServer({ coordinator: w.driver.coordinator, coordination: w.driver.coordination, principal, repoIds: ['repo-a'], maxWaitMs: 1000, maxMessageBytes: 16_384, takeToolQuota: async () => ({ ok: true }) });
  await mcp.handle({ jsonrpc: '2.0', id: 0, method: 'initialize', params: { protocolVersion: '2025-11-25', capabilities: {}, clientInfo: { name: 'pf7-test', version: '1' } } }); await mcp.handle({ jsonrpc: '2.0', method: 'notifications/initialized' });
  const mcpResult = await mcp.handle({ jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'fleet_provider_status', arguments: { repoId: 'repo-a', limit: 1 } } }); assert.equal(mcpResult.result.isError, false); assert.deepEqual(mcpResult.result.structuredContent.providers, completed.providers); assert.deepEqual(mcpResult.result.structuredContent.historicalProcessing, completed.historicalProcessing);
  const refusedMcp = new McpFleetServer({ coordinator: w.driver.coordinator, coordination: w.driver.coordination, principal: { ...principal, capabilities: ['control'] }, repoIds: ['repo-a'], maxWaitMs: 1000, maxMessageBytes: 16_384, takeToolQuota: async () => ({ ok: true }) }); await refusedMcp.handle({ jsonrpc: '2.0', id: 0, method: 'initialize', params: { protocolVersion: '2025-11-25', capabilities: {}, clientInfo: { name: 'pf7-test', version: '1' } } }); await refusedMcp.handle({ jsonrpc: '2.0', method: 'notifications/initialized' }); const denied = await refusedMcp.handle({ jsonrpc: '2.0', id: 2, method: 'tools/call', params: { name: 'fleet_provider_status', arguments: { repoId: 'repo-a' } } }); assert.equal(denied.result.structuredContent.error.code, 'forbidden');
  const secondRaw = Buffer.from(JSON.stringify({ deliveryId: 'provider-read-second', occurredAt: '2026-07-13T06:00:00.000Z', sequence: 1, coordinates: [coordinate] })); await w.driver.coordinator.receiveProviderDelivery('fixture.green-two', { mode: 'webhook', raw: secondRaw });
  const all = w.driver.coordinator.readProviderStatus({ limit: 4 }, { repoId: 'repo-a' }); const firstPage = w.driver.coordinator.readProviderStatus({ limit: 1 }, { repoId: 'repo-a' }); const secondPage = w.driver.coordinator.readProviderStatus({ after: firstPage.nextAfter, limit: 1 }, { repoId: 'repo-a' });
  assert.equal(all.currentProcessing.length, 1); assert.equal(all.historicalProcessing.length, 1); assert.match(firstPage.nextAfter, /^provider-processing:[a-f0-9]{64}$/); assert.equal(secondPage.nextAfter, null); assert.deepEqual([...firstPage.currentProcessing, ...firstPage.historicalProcessing, ...secondPage.currentProcessing, ...secondPage.historicalProcessing].map((row) => row.processingId).sort(), [...all.currentProcessing, ...all.historicalProcessing].map((row) => row.processingId).sort());
  w.driver.close();
});

test('PF7: provider, state-row, processing, and byte ceilings fail closed at max plus one', async () => {
  const providerBound = await world({ providerRead: { maxProviders: 1, maxProcessing: 4, maxStateRows: 32, maxBytes: 8192 } }); const raw = Buffer.from(JSON.stringify({ deliveryId: 'provider-bound-second', occurredAt: '2026-07-13T06:00:00.000Z', sequence: 1, coordinates: [coordinate] })); await providerBound.driver.coordinator.receiveProviderDelivery('fixture.green-two', { mode: 'webhook', raw }); assert.throws(() => providerBound.driver.coordinator.readProviderStatus({}, { repoId: 'repo-a' }), (error) => error.code === 'provider_read_oversize'); providerBound.driver.close();
  const stateBound = await world({ providerRead: { maxProviders: 4, maxProcessing: 4, maxStateRows: 1, maxBytes: 8192 } }); assert.throws(() => stateBound.driver.coordinator.readProviderStatus({}, { repoId: 'repo-a' }), (error) => error.code === 'provider_read_oversize'); stateBound.driver.close();
  const byteBound = await world({ providerRead: { maxProviders: 4, maxProcessing: 4, maxStateRows: 32, maxBytes: 128 } }); assert.throws(() => byteBound.driver.coordinator.readProviderStatus({}, { repoId: 'repo-a' }), (error) => error.code === 'provider_read_oversize'); byteBound.driver.close();
  const limitBound = await world({ providerRead: { maxProviders: 4, maxProcessing: 1, maxStateRows: 32, maxBytes: 8192 } }); assert.throws(() => limitBound.driver.coordinator.readProviderStatus({ limit: 2 }, { repoId: 'repo-a' }), (error) => error.code === 'provider_read_invalid'); limitBound.driver.close();
});

test('AF4: official npm system alias is closed and no extra identity authority is accepted', async () => {
  const accepted = await world({ identityExtra: { system: 'NPM' } }); assert.equal((await accepted.driver.coordinator.reconcileProviderProcessing(accepted.admitted.processing.id)).result, 'ignored_non_adverse'); accepted.driver.close();
  const rejected = await world({ identityExtra: { system: 'NPM', registry: 'attacker.example' } }); await assert.rejects(rejected.driver.coordinator.reconcileProviderProcessing(rejected.admitted.processing.id), (error) => error.code === 'reuse_evidence_diverged'); assert.equal(rejected.driver.coordination.providerProcessing(rejected.admitted.processing.id).status, 'pending'); rejected.driver.close();
});

test('AF4/AF5/AF9: seedless adverse refresh retains a monotonic contribution, aggregate guard, and causal lineage', async () => {
  const w = await world({ adverse: true }); const result = await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id);
  assert.equal(result.result, 'guarded_adverse'); assert.equal(result.processing.status, 'guarded_adverse'); assert.equal(w.driver.coordination.pendingProviderReconciliation('repo-a', coordinate).length, 0);
  const state = w.driver.coordination.reuseAdverseState('repo-a', coordinate); assert.equal(state.blocked, true); assert.equal(state.manual, null); assert.equal(state.provider.contributionIds.length, 1); assert.deepEqual(state.provider.advisoryIds, ['OSV-adverse']);
  const snapshot = w.driver.coordination.snapshot(); assert.equal(snapshot.reuseProviderContributions.length, 1); const finding = snapshot.knowledge.nodes.find((node) => node.promotion?.trigger === 'provider.risk'); const official = snapshot.knowledge.nodes.find((node) => node.promotion?.trigger === 'provider.official' && node.factDigest === snapshot.reuseProviderContributions[0].officialFactDigest); assert.equal(finding.type, 'Finding'); assert.equal(finding.grounding, 'derived'); assert.equal(official.type, 'Source'); assert.ok(snapshot.knowledge.edges.some((edge) => edge.type === 'DerivedFrom' && edge.from === finding.id && edge.to === official.id)); assert.ok(snapshot.knowledge.edges.some((edge) => edge.type === 'DerivedFrom' && edge.from === official.id && edge.to === w.admitted.receipt.nodeId));
  const counts = { invokes: w.state.invokes, reverifies: w.state.reverifies }; const retry = await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id); assert.equal(retry.result, 'idempotent'); assert.deepEqual({ invokes: w.state.invokes, reverifies: w.state.reverifies }, counts); w.driver.close();
  const replay = createDriver(w.options); assert.equal(replay.coordination.reuseProviderGuard('repo-a', coordinate).blocked, true); assert.equal(replay.coordination.providerProcessing(w.admitted.processing.id).status, 'guarded_adverse'); replay.close();
});

test('AF5: independent provider observations union without replacing either immutable contribution', async () => {
  const w = await world({ adverse: true }); await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id);
  const raw = Buffer.from(JSON.stringify({ deliveryId: 'delivery-green-two', occurredAt: '2026-07-13T06:00:00.000Z', sequence: 1, coordinates: [coordinate] })); const second = await w.driver.coordinator.receiveProviderDelivery('fixture.green-two', { mode: 'webhook', raw }); await w.driver.coordinator.reconcileProviderProcessing(second.processing.id);
  const guard = w.driver.coordination.reuseProviderGuard('repo-a', coordinate); assert.equal(guard.blocked, true); assert.equal(guard.contributionIds.length, 2); assert.equal(new Set(guard.contributionIds).size, 2); assert.equal(w.driver.coordination.snapshot().reuseProviderContributions.length, 2); w.driver.close();
});

test('AF3/AF5/AF6: mixed green/adverse coordinates complete in one append without exposing a pending prefix', async () => {
  const second = { ecosystem: 'npm', package: '@scope/provider-green-two', version: '2.0.0' }; const key = (value) => `${value.ecosystem}\0${value.package}\0${value.version}`; const coordinates = [coordinate, second].sort((a, b) => key(a) < key(b) ? -1 : key(a) > key(b) ? 1 : 0); const w = await world({ coordinates, adversePackages: [coordinate.package] });
  const result = await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id); assert.equal(result.result, 'guarded_adverse'); assert.equal(result.processing.observations.filter((row) => row.adverse).length, 1); assert.equal(coordinates.every((value) => w.driver.coordination.pendingProviderReconciliation('repo-a', value).length === 0), true);
  const snapshot = w.driver.coordination.snapshot(); assert.equal(snapshot.reuseProviderContributions.length, 1); assert.equal(snapshot.knowledge.nodes.filter((node) => node.promotion?.trigger === 'provider.official').length, 2); assert.equal(w.driver.coordination.events().filter((event) => event.kind === 'knowledge.reuse_provider_guarded').length, 1); w.driver.close();
});

test('AF3/AF5: a later green observation from another provider cannot clear an existing aggregate guard', async () => {
  const w = await world({ adverse: true }); await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id); const before = w.driver.coordination.reuseProviderGuard('repo-a', coordinate); w.state.adverse = false;
  const raw = Buffer.from(JSON.stringify({ deliveryId: 'delivery-green-after-adverse', occurredAt: '2026-07-13T06:00:00.000Z', sequence: 1, coordinates: [coordinate] })); const green = await w.driver.coordinator.receiveProviderDelivery('fixture.green-two', { mode: 'webhook', raw }); const checked = await w.driver.coordinator.reconcileProviderProcessing(green.processing.id); assert.equal(checked.result, 'ignored_non_adverse'); assert.deepEqual(w.driver.coordination.reuseProviderGuard('repo-a', coordinate), before); w.driver.close();
});

test('AF5/AF6: policy A to B stales only the aggregate projection while immutable contributions remain blocking', async () => {
  const w = await world({ adverse: true }); await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id); const before = w.driver.coordination.snapshot(); const guardA = w.driver.coordination.reuseProviderGuard('repo-a', coordinate); const aggregateA = `finding:reuse-provider-aggregate:${guardA.guardDigest}`; w.driver.close();
  w.state.policyProjection = { ...policyProjection, minScorecard: 8 }; w.options.capabilities = { 'cartographer-quartermaster': quartermaster(w.state) }; const policyBHash = sha(w.state.policyProjection); const b = createDriver(w.options); const guardB = b.coordination.reuseProviderGuard('repo-a', coordinate);
  assert.equal(guardB.blocked, true); assert.equal(guardB.policyStale, true); assert.equal(guardB.requiredPolicyHash, policyBHash); assert.equal(guardB.guardDigest, guardA.guardDigest); assert.deepEqual(b.coordination.snapshot().reuseProviderContributions, before.reuseProviderContributions);
  const snapshot = b.coordination.snapshot(); const oldAggregate = snapshot.knowledge.nodes.find((node) => node.id === aggregateA); assert.ok(oldAggregate.validTo); assert.equal(oldAggregate.validityVersion, 2); const constraint = b.coordination.reusePolicyState('repo-a').constraintId; assert.ok(snapshot.knowledge.edges.some((edge) => edge.type === 'Affects' && edge.from === constraint && edge.to === aggregateA)); assert.equal(b.coordination.reuseAdverseState('repo-a', coordinate).blocked, true); b.close();
  const replay = createDriver(w.options); assert.equal(replay.coordination.reuseProviderGuard('repo-a', coordinate).policyStale, true); assert.deepEqual(replay.coordination.snapshot().reuseProviderContributions, before.reuseProviderContributions); replay.close();
});

test('AF6: adverse append failure leaves the whole processing root pending with no partial guard or graph projection', async () => {
  const w = await world({ adverse: true }); const append = w.driver.coordination._appendFile; w.driver.coordination._appendFile = (...args) => { if (String(args[1]).includes('knowledge.reuse_provider_guarded')) throw new Error('adverse ledger unavailable'); return append(...args); };
  await assert.rejects(w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id), /adverse ledger unavailable|coordination/); assert.equal(w.driver.coordination.providerProcessing(w.admitted.processing.id).status, 'pending'); assert.equal(w.driver.coordination.pendingProviderReconciliation('repo-a', coordinate).length, 1); assert.equal(w.driver.coordination.reuseProviderGuard('repo-a', coordinate), null); assert.equal(w.driver.coordination.snapshot().knowledge.nodes.some((node) => node.promotion?.trigger === 'provider.risk'), false); w.driver.coordination._appendFile = append; w.driver.close();
});

test('AF10: zero-network replay rejects mutation of an adverse contribution projection', async () => {
  const w = await world({ adverse: true }); await w.driver.coordinator.reconcileProviderProcessing(w.admitted.processing.id); w.driver.close();
  const path = join(w.options.logDir, 'coordination', 'events.jsonl'); const events = readFileSync(path, 'utf8').trimEnd().split('\n').map(JSON.parse); const guarded = events.find((event) => event.kind === 'knowledge.reuse_provider_guarded'); guarded.payload.observations[0].contribution.advisoryIds = ['OSV-substituted']; writeFileSync(path, `${events.map(JSON.stringify).join('\n')}\n`);
  assert.throws(() => createDriver(w.options), (error) => error.code === 'provider_contribution_conflict');
});
