import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import { CairnRunScorecard, McpFleetServer, MockAdapter, WebNorthbound, createBrief, createDriver } from '../src/index.mjs';

const root = (name) => mkdtempSync(join(tmpdir(), `baton-route-stats-${name}-`));
const canonical = (value) => Array.isArray(value) ? value.map(canonical) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])])) : value;
const sha = (value) => createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');
const until = async (fn, label, timeoutMs = 5000) => { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { const value = await fn(); if (value) return value; await new Promise((resolve) => setTimeout(resolve, 5)); } throw new Error(`timed out waiting for ${label}`); };
function repo() { const path = root('repo'); execFileSync('git', ['init', '-q'], { cwd: path }); execFileSync('git', ['-c', 'user.name=Baton Test', '-c', 'user.email=baton@example.test', 'commit', '--allow-empty', '-q', '-m', 'base'], { cwd: path }); return path; }
function brief(target, command = `test -s ${target}`) { return createBrief({ goal: `write ${target}`, constraints: [], pathScope: [target], definitionOfDone: `${target} passes`, verification: { command, expectExit: 0, timeoutMs: 5000 }, budget: { tokens: 1000, usd: 1, wallMin: 1 } }); }
function adapter({ harness = 'mock-route', version = '1', family = 'mock-family', target = 'done.txt', content = 'done\n', delayMs } = {}) { const instance = new MockAdapter({ card: { harness, version }, scenario: { outcome: 'completed', edits: [{ path: target, content, ...(delayMs ? { delayMs } : {}) }] } }); const base = instance.card.bind(instance); instance.card = () => ({ ...base(), modelSelection: { mode: 'exact', configuredDefault: `${harness}-model`, available: [`${harness}-model`], family, acceptedPrefixes: [`${harness}-`], acceptedAliases: [], reasoningEffort: ['low'], serviceTier: null, provenance: 'test', refreshedAt: null } }); return instance; }
function world(overrides = {}) { const repoRoot = repo(); const logDir = root('log'); const artifactRoot = root('artifacts'); const primary = overrides.adapter ?? adapter(overrides); const options = { repoRoot, repoId: 'repo-route', logDir, adapters: { primary }, now: overrides.now ?? (() => Date.parse('2026-07-13T10:00:00.000Z')), routeLearningPolicy: { mode: 'auto', halfLifeMs: 604_800_000, explorationConstant: 0.5, seedDiscount: 0.5, minSamplesForAdaptive: 2, defaultPriorSuccessRate: 0.5 }, capabilityFactories: { cairn: ({ coordination, readOperational, router }) => new CairnRunScorecard({ coordination, readOperational, artifactRoot, routeAdvisor: router, routeAdvice: { maxCandidates: 4, maxTaskTypeBytes: 64, maxRows: 4, maxBytes: 8192 } }) }, maxCapabilityBudgetTokens: 10_000, maxCapabilityEnvelopeBytes: 128 * 1024 }; return { driver: createDriver(options), options, primary }; }

test('RS1-RS3: hub-verified terminal atomically records one exact route observation and graph node', async () => {
  const w = world(); const terminal = w.driver.coordination.transitionTaskWithArtifacts.bind(w.driver.coordination); let terminalArgs = null; w.driver.coordination.transitionTaskWithArtifacts = (...args) => { terminalArgs = structuredClone(args); return terminal(...args); };
  const handle = await w.driver.coordinator.spawn('primary', brief('done.txt'), { taskId: 'route-win', taskType: 'implementation', model: 'mock-route-model', effort: 'low' }); await until(async () => (await w.driver.coordinator.result(handle.id)).ready, 'verified route task');
  const rows = w.driver.coordination.routeObservations(); assert.equal(rows.length, 1); const row = rows[0]; assert.equal(row.taskId, 'route-win'); assert.equal(row.taskType, 'implementation'); assert.equal(row.modelFamily, 'mock-family'); assert.equal(row.verifiedWin, true); assert.match(row.routeKey, /mock-route-model/); assert.equal(w.driver.coordination.events().filter((event) => event.kind === 'route.outcome_observed').length, 1);
  const beforeRetry = w.driver.coordination.events().length; const retry = terminal(...structuredClone(terminalArgs)); assert.equal(retry.result, 'idempotent'); assert.equal(w.driver.coordination.events().length, beforeRetry); const changed = structuredClone(terminalArgs); changed[3].routeObservation.modelFamily = 'substituted-family'; assert.throws(() => terminal(...changed), (error) => error.code === 'route_observation_conflict'); assert.equal(w.driver.coordination.events().length, beforeRetry);
  const snapshot = w.driver.coordination.snapshot(); const node = snapshot.knowledge.nodes.find((item) => item.type === 'RouteStat' && item.taskId === 'route-win'); assert.ok(node); assert.ok(snapshot.knowledge.edges.some((edge) => edge.type === 'ObservedIn' && edge.from === node.id && edge.to === 'task:route-win'));
  const firstRouter = w.driver.router.snapshot(); assert.deepEqual(firstRouter.appliedTaskIds, ['route-win']); await w.driver.coordinator.kill(handle.id, 'policy'); w.driver.close();
  const replay = createDriver({ ...w.options, now: () => Date.parse('2026-07-20T10:00:00.000Z') }); assert.deepEqual(replay.coordination.routeObservations(), rows); assert.deepEqual(replay.router.snapshot().buckets, firstRouter.buckets); assert.deepEqual(replay.router.snapshot().appliedTaskIds, ['route-win']); replay.close();
});

test('RS1/RS5: verified failure learns one loss while pre-verification cancellation learns nothing', async () => {
  const failed = world({ target: 'expected.txt', content: 'wrong\n' }); writeFileSync(join(failed.options.repoRoot, 'expected.txt'), 'correct\n'); execFileSync('git', ['add', 'expected.txt'], { cwd: failed.options.repoRoot }); execFileSync('git', ['-c', 'user.name=Baton Test', '-c', 'user.email=baton@example.test', 'commit', '-q', '-m', 'passing base'], { cwd: failed.options.repoRoot }); const bad = await failed.driver.coordinator.spawn('primary', brief('expected.txt', "grep -q '^correct$' expected.txt"), { taskId: 'route-loss', taskType: 'review', model: 'mock-route-model', effort: 'low' }); const badResult = await until(async () => { const result = await failed.driver.coordinator.result(bad.id); return result.ready ? result : null; }, 'failed verification'); assert.equal(badResult.status, 'failed'); assert.equal(badResult.verdict.failureOwnership, 'candidate'); assert.equal(failed.driver.coordination.routeObservations()[0].verifiedWin, false); await failed.driver.coordinator.kill(bad.id, 'policy'); failed.driver.close();

  const cancelled = world({ target: 'later.txt', delayMs: 500 }); const active = await cancelled.driver.coordinator.spawn('primary', brief('later.txt'), { taskId: 'route-cancel', taskType: 'implementation', model: 'mock-route-model', effort: 'low' }); await cancelled.driver.coordinator.kill(active.id, 'policy'); assert.deepEqual(cancelled.driver.coordination.routeObservations(), []); cancelled.driver.close();
});

test('RS2/RS4/RS5: exact policy is pinned and terminal-batch failure exposes no route or live-router update', async () => {
  const w = world(); const before = w.driver.router.snapshot(); const append = w.driver.coordination._appendFile; w.driver.coordination._appendFile = (...args) => { if (String(args[1]).includes('route.outcome_observed')) throw new Error('route ledger unavailable'); return append(...args); };
  const handle = await w.driver.coordinator.spawn('primary', brief('done.txt'), { taskId: 'route-atomic', taskType: 'implementation', model: 'mock-route-model', effort: 'low' }); await until(() => w.driver.coordinator._fatalError, 'atomic coordination poison'); assert.throws(() => w.driver.coordinator.tick(), (error) => error.code === 'coordination_write_unavailable'); assert.deepEqual(w.driver.coordination.routeObservations(), []); assert.deepEqual(w.driver.router.snapshot(), before); w.driver.coordination._appendFile = append; await w.driver.coordinator.kill(handle.id, 'policy', { emergency: true }); w.driver.close();
  assert.throws(() => createDriver({ ...w.options, routeLearningPolicy: { mode: 'auto' } }), /route learning policy/);
});

test('RS6-RS8: Cairn advice is bounded, deterministic, read-only, and caller outcomes are impossible', async () => {
  const w = world(); const handle = await w.driver.coordinator.spawn('primary', brief('done.txt'), { taskId: 'route-advice', taskType: 'implementation', model: 'mock-route-model', effort: 'low' }); await until(async () => (await w.driver.coordinator.result(handle.id)).ready, 'advice evidence'); const observed = w.driver.coordination.routeObservations()[0];
  const other = JSON.stringify(['other-harness', '1', 'other-model', 'low', 'other-family', 'implementation']); const args = { taskType: 'implementation', observedAt: '2026-07-13T10:00:00.000Z', candidates: [{ routeKey: observed.routeKey, modelFamily: observed.modelFamily, concurrencyCeiling: 1, inFlight: 0 }, { routeKey: other, modelFamily: 'other-family', concurrencyCeiling: 1, inFlight: 1 }] };
  const before = w.driver.router.snapshot(); const result = await w.driver.coordinator.invokeCapability('cairn', 'route.advice', args, { actor: 'orchestrator', budgetTokens: 4000 }); assert.equal(result.status, 'ok'); assert.equal(result.payload[0].selectedRouteKey, observed.routeKey); assert.equal(result.payload[0].rows.find((row) => row.routeKey === other).reason, 'concurrency_saturated'); assert.equal(result.provenance.routingMutationAuthority, false); assert.deepEqual(w.driver.router.snapshot(), before);
  const reverified = await w.driver.coordinator.reverifyCapability('cairn', 'route.advice', result, args, { actor: 'orchestrator', budgetTokens: 4000 }); assert.equal(reverified.status, 'ok'); assert.equal(reverified.payload[0].ok, true);
  const origin = 'https://control.route.test'; const principal = { userId: 'alice', sessionId: 'route-web', credentialId: 'route-cred', authMethod: 'cookie', csrfToken: 'csrf', expiresAt: '2099-01-01T00:00:00.000Z', revoked: false, capabilities: ['control'], repoIds: ['repo-route'] }; const web = new WebNorthbound({ coordinator: w.driver.coordinator, coordination: w.driver.coordination, repoIds: ['repo-route'], allowedOrigins: [origin] }); const webResult = await web.execute({ principal, origin, csrfToken: 'csrf', remoteAddress: '127.0.0.1', transport: 'https' }, { schemaVersion: 1, commandId: 'route-web', idempotencyKey: 'route-web', command: 'capability_invoke', repoId: 'repo-route', origin, args: { name: 'cairn', op: 'route.advice', action: 'invoke', args, budgetTokens: 4000 } }); assert.equal(webResult.status, 200); assert.equal(webResult.body.result.payload[0].adviceDigest, result.payload[0].adviceDigest);
  const mcp = new McpFleetServer({ coordinator: w.driver.coordinator, coordination: w.driver.coordination, principal: { userId: 'bob', sessionId: 'route-mcp', capabilities: ['control'], repoIds: ['repo-route'], expiresAt: '2099-01-01T00:00:00.000Z', revoked: false }, repoIds: ['repo-route'], maxWaitMs: 1000, maxMessageBytes: 128 * 1024, takeToolQuota: async () => ({ ok: true }) }); await mcp.handle({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-11-25', capabilities: {}, clientInfo: { name: 'route-test', version: '1' } } }); await mcp.handle({ jsonrpc: '2.0', method: 'notifications/initialized' }); const mcpResult = await mcp.handle({ jsonrpc: '2.0', id: 2, method: 'tools/call', params: { name: 'fleet_capability_invoke', arguments: { repoId: 'repo-route', idempotencyKey: 'route-mcp', name: 'cairn', op: 'route.advice', action: 'invoke', args, budgetTokens: 4000 } } }); assert.equal(mcpResult.result.isError, false); assert.equal(mcpResult.result.structuredContent.payload[0].adviceDigest, result.payload[0].adviceDigest);
  await assert.rejects(w.driver.coordinator.invokeCapability('cairn', 'route.advice', { ...args, outcome: true }, { actor: 'orchestrator', budgetTokens: 4000 }), (error) => error.code === 'route_advice_invalid');
  await assert.rejects(w.driver.coordinator.invokeCapability('cairn', 'route.advice', { ...args, candidates: Array.from({ length: 5 }, (_, index) => ({ routeKey: JSON.stringify([`h${index}`, '1', `m${index}`, 'low', `f${index}`, 'implementation']), modelFamily: `f${index}`, concurrencyCeiling: 1, inFlight: 0 })) }, { actor: 'orchestrator', budgetTokens: 4000 }), (error) => error.code === 'route_advice_invalid');
  await w.driver.coordinator.kill(handle.id, 'policy'); w.driver.close();
});

test('RS2-RS4/RS7: replay rejects policy and observation mutation, and later evidence invalidates old advice', async () => {
  const w = world(); const first = await w.driver.coordinator.spawn('primary', brief('done.txt'), { taskId: 'route-first', taskType: 'implementation', model: 'mock-route-model', effort: 'low' }); await until(async () => (await w.driver.coordinator.result(first.id)).ready, 'first evidence'); const row = w.driver.coordination.routeObservations()[0]; const args = { taskType: 'implementation', observedAt: '2026-07-13T10:00:00.000Z', candidates: [{ routeKey: row.routeKey, modelFamily: row.modelFamily, concurrencyCeiling: 1, inFlight: 0 }] }; const claim = await w.driver.coordinator.invokeCapability('cairn', 'route.advice', args, { actor: 'orchestrator', budgetTokens: 4000 });
  const second = await w.driver.coordinator.spawn('primary', brief('done.txt'), { taskId: 'route-second', taskType: 'implementation', model: 'mock-route-model', effort: 'low' }); await until(async () => (await w.driver.coordinator.result(second.id)).ready, 'second evidence'); const drift = await w.driver.coordinator.reverifyCapability('cairn', 'route.advice', claim, args, { actor: 'orchestrator', budgetTokens: 4000 }); assert.equal(drift.status, 'diverged'); await w.driver.coordinator.kill(first.id, 'policy'); await w.driver.coordinator.kill(second.id, 'policy'); w.driver.close();
  assert.throws(() => createDriver({ ...w.options, routeLearningPolicy: { ...w.options.routeLearningPolicy, halfLifeMs: 60_000 } }), (error) => error.code === 'route_observation_integrity');
  const path = join(w.logDir ?? w.options.logDir, 'coordination', 'events.jsonl'); const original = readFileSync(path, 'utf8'); let events = original.trimEnd().split('\n').map(JSON.parse); let observed = events.find((event) => event.kind === 'route.outcome_observed'); observed.idempotencyKey = `${observed.idempotencyKey}:substituted`; writeFileSync(path, `${events.map(JSON.stringify).join('\n')}\n`); assert.throws(() => createDriver(w.options), (error) => error.code === 'route_observation_integrity'); writeFileSync(path, original);
  events = original.trimEnd().split('\n').map(JSON.parse); observed = events.find((event) => event.kind === 'route.outcome_observed'); observed.payload.verifiedWin = !observed.payload.verifiedWin; const { observationDigest, ...core } = observed.payload; observed.payload.observationDigest = sha({ ...core, idempotencyKey: observed.idempotencyKey }); writeFileSync(path, `${events.map(JSON.stringify).join('\n')}\n`); assert.throws(() => createDriver(w.options), (error) => error.code === 'route_observation_integrity'); writeFileSync(path, original);
  events = original.trimEnd().split('\n').map(JSON.parse); observed = events.find((event) => event.kind === 'route.outcome_observed'); observed.payload.modelFamily = 'substituted-family'; writeFileSync(path, `${events.map(JSON.stringify).join('\n')}\n`); assert.throws(() => createDriver(w.options), (error) => error.code === 'route_observation_integrity');
});
