// Issue #261: conformance for the ONE surface-truth derivation module
// (impl/scripts/surface-truth.mjs). Every export must agree with the committed inventory
// artifact (regenerated by buildSurfaceInventoryArtifact through the surface gate) and with the
// src tables it claims to derive from — a derivation that drifts from either witness fails here,
// so the tests importing these derivations never re-type a literal to keep one honest.
//
// All-green by construction at HEAD: this file pins the derivations, not staged behavior.

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  applicationCardCommands, BYTE_STABLE_COMMAND_KEYS, combinedMcpToolNames, commandKeys,
  mockApplicationCard, northboundApplicationToolNames, ordinaryMcpToolNames, swarmVerbs, webCardCommands,
} from '../scripts/surface-truth.mjs';
import { APPLICATION_COMMAND_DEFINITIONS } from '../src/application.mjs';
import { APPLICATION_SEMANTIC_REGISTRY } from '../src/application-semantics.mjs';
import { SWARM_COMMAND_DEFINITIONS } from '../src/swarm-contract.mjs';
import { McpFleetServer, mcpApplicationToolNames } from '../src/mcp-northbound.mjs';
import { CORE_TOOL_NAMES } from '../src/mcp-core-tools.mjs';

test('commandKeys: the live table is the one byte-stable derivation (issue #582: no committed census)', () => {
  assert.equal(Object.isFrozen(BYTE_STABLE_COMMAND_KEYS), true, 'the derivation is frozen');
  assert.deepEqual(commandKeys(), [...BYTE_STABLE_COMMAND_KEYS],
    'the table key list is the one derivation (docs/36 §9 M3)');
  // The swarm block leads the table exactly as the contract spreads it.
  assert.deepEqual(commandKeys().slice(0, swarmVerbs().length), swarmVerbs(),
    'the swarm verbs lead the command table');
  assert.deepEqual(commandKeys().slice(swarmVerbs().length), [...BYTE_STABLE_COMMAND_KEYS].slice(swarmVerbs().length),
    'the legacy tail is byte-stable too');
});

test('swarmVerbs: the twelve docs/39 verbs (#296 added swarm.integrate, #311 the peer channel, #598 removed swarm.check), one source in the swarm contract', () => {
  assert.deepEqual(swarmVerbs(), [...Object.keys(SWARM_COMMAND_DEFINITIONS)],
    'the swarm verbs derive from the contract table in contract order');
  assert.equal(swarmVerbs().length, 12);
});

test('webCardCommands: the sorted web-admitted card plus the wave direct ports, deterministic', () => {
  // Independent re-derivation: web-admitted table names ∪ the six wave direct ports, sorted.
  const ports = ['waves.list', 'waves.progress', 'waves.run', 'waves.send', 'waves.start', 'waves.stop'];
  const derived = [
    ...commandKeys().filter((name) => APPLICATION_COMMAND_DEFINITIONS[name].web),
    ...ports,
  ].sort();
  assert.deepEqual(webCardCommands(), derived);
  for (const port of ports) {
    assert.equal(Object.hasOwn(APPLICATION_COMMAND_DEFINITIONS, port), false,
      `${port} is a direct port, never a table entry`);
  }
});

test('ordinaryMcpToolNames: the shipped ordinary surface is the core table, deterministic', () => {
  const names = ordinaryMcpToolNames();
  assert.deepEqual(names, ordinaryMcpToolNames(), 'the served order is deterministic');
  assert.deepEqual([...names].sort(), [...CORE_TOOL_NAMES].sort(),
    'the shipped ordinary surface IS the core table the production wrapper advertises (docs/49 §2)');
  assert.ok(names.includes('baton_swarm'), 'the swarm family rides the ordinary surface as its verb tool');
  assert.ok(!names.some((name) => /shutdown|fleet_/u.test(name)), 'no host-lifecycle or fleet_ tool');
});

test('northboundApplicationToolNames: the raw northbound table is the flat list the phase pins read', () => {
  const names = northboundApplicationToolNames();
  assert.deepEqual(names, northboundApplicationToolNames(), 'the served order is deterministic');
  assert.deepEqual([...names].sort(), mcpApplicationToolNames(),
    'the raw application table equals mcpApplicationToolNames()');
  assert.equal(new Set(names).size, names.length, 'no duplicate tool names');
  assert.ok(names.includes('baton_swarm_list'), 'the flat swarm family rides the raw application table');
  assert.ok(!names.some((name) => /shutdown|fleet_/u.test(name)), 'no host-lifecycle or fleet_ tool');
});

test('combinedMcpToolNames: deterministic and a superset of the raw ordinary table', () => {
  const names = combinedMcpToolNames();
  assert.equal(new Set(names).size, names.length, 'no duplicate tool names');
  // The combined profile is the RAW table's superset (its flat tools plus the kernel families).
  // The shipped ordinary surface is the core verb-tools, a projection the production wrapper
  // installs on `surface: 'application'` alone — docs/49 §9 leaves advanced/combined on the flat
  // table, so the core spellings are not part of this profile.
  const flat = new Set([...northboundApplicationToolNames()].sort());
  for (const name of flat) assert.ok(names.includes(name), `${name} stays served on combined`);
});

test('applicationCardCommands: table keys first, then the M4b canonical names, disjoint and derived', () => {
  const commands = applicationCardCommands();
  const keys = commandKeys();
  assert.deepEqual(commands.slice(0, keys.length), keys, 'the table keys lead in insertion order');
  const canonicalTail = commands.slice(keys.length);
  assert.equal(new Set([...keys]).intersection(new Set(canonicalTail)).size, 0,
    'the canonical names are never table keys (docs/36 §9 M4b)');
  const byKey = new Map(APPLICATION_SEMANTIC_REGISTRY.canonicalOperations.map((op) => [op.key, op]));
  for (const name of canonicalTail) {
    const operation = byKey.get(name);
    assert.ok(operation, `${name} is a registered canonical operation`);
    assert.equal(operation.profile, 'ordinary', `${name} is an ordinary operation`);
  }
});

test('mockApplicationCard: a table-derived card that satisfies the real server constructor', () => {
  const card = mockApplicationCard('repo-mock');
  assert.deepEqual(card, { schemaVersion: 1, repoId: 'repo-mock', commands: applicationCardCommands() });
  for (const [name, definition] of Object.entries(APPLICATION_COMMAND_DEFINITIONS)) {
    if (definition.web || definition.mcp) {
      assert.ok(card.commands.includes(name), `${name} is advertised to every admitting surface`);
    }
  }
  const coordination = Object.fromEntries(
    ['admitMcpCall', 'completeMcpCall', 'failMcpCall', 'mcpCall', 'recordMcpAudit']
      .map((method) => [method, async () => ({})]),
  );
  const common = {
    coordinator: {}, coordination,
    principal: {
      userId: 'surface-truth-test', sessionId: 'surface-truth-test',
      capabilities: ['observe', 'control', 'approve', 'emergency_stop'],
      repoIds: ['repo-mock'], expiresAt: '9999-01-01T00:00:00.000Z', revoked: false,
    },
    repoIds: ['repo-mock'],
    application: {
      repoId: 'repo-mock', card: () => ({ ...card }),
      command: async () => ({}), authorizeReplay: async () => true,
    },
    applicationOwned: false,
  };
  assert.equal(new McpFleetServer({ ...common, surface: 'application' }).toolDefinitions.length,
    northboundApplicationToolNames().length);
  assert.equal(new McpFleetServer({ ...common, surface: 'combined' }).toolDefinitions.length,
    combinedMcpToolNames().length);
});
