// Issue #261: conformance for the ONE surface-truth derivation module
// (impl/scripts/surface-truth.mjs). Every export must agree with the committed inventory
// artifact (regenerated by buildSurfaceInventoryArtifact through the surface gate) and with the
// src tables it claims to derive from — a derivation that drifts from either witness fails here,
// so the tests importing these derivations never re-type a literal to keep one honest.
//
// All-green by construction at HEAD: this file pins the derivations, not staged behavior.

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  applicationCardCommands, BYTE_STABLE_COMMAND_KEYS, combinedMcpToolNames, commandKeys,
  mockApplicationCard, ordinaryMcpToolNames, swarmVerbs, webCardCommands,
} from '../scripts/surface-truth.mjs';
import { APPLICATION_COMMAND_DEFINITIONS } from '../src/application.mjs';
import { APPLICATION_SEMANTIC_REGISTRY } from '../src/application-semantics.mjs';
import { SWARM_COMMAND_DEFINITIONS } from '../src/swarm-contract.mjs';
import { McpFleetServer, mcpApplicationToolNames } from '../src/mcp-northbound.mjs';

const artifact = JSON.parse(
  readFileSync(new URL('../scripts/surface-inventory-artifact.json', import.meta.url), 'utf8'),
);

test('commandKeys: the live table equals the committed byte-stable witness and the artifact count', () => {
  assert.equal(Object.isFrozen(BYTE_STABLE_COMMAND_KEYS), true, 'the committed witness is frozen');
  assert.deepEqual(commandKeys(), [...BYTE_STABLE_COMMAND_KEYS],
    'the table key list is byte-stable against the committed witness (docs/36 §9 M3)');
  assert.equal(commandKeys().length, artifact.counts.applicationCommandDefinitions,
    'the key count matches the committed inventory artifact');
  // The swarm block leads the table exactly as the contract spreads it.
  assert.deepEqual(commandKeys().slice(0, swarmVerbs().length), swarmVerbs(),
    'the swarm verbs lead the command table');
  assert.deepEqual(commandKeys().slice(swarmVerbs().length), [...BYTE_STABLE_COMMAND_KEYS].slice(swarmVerbs().length),
    'the legacy tail is byte-stable too');
});

test('swarmVerbs: the eleven docs/39 verbs (#296 added swarm.integrate), one source in the swarm contract', () => {
  assert.deepEqual(swarmVerbs(), [...Object.keys(SWARM_COMMAND_DEFINITIONS)],
    'the swarm verbs derive from the contract table in contract order');
  assert.equal(swarmVerbs().length, 11);
});

test('webCardCommands: the sorted web-admitted card plus the wave direct ports, byte-stable against the artifact', () => {
  assert.deepEqual(webCardCommands(), artifact.profiles['web.bus'],
    'the derived web card equals the committed web.bus profile');
  assert.equal(webCardCommands().length, artifact.counts.webBusCommands);
  // Independent re-derivation: web-admitted table names ∪ the six wave direct ports, sorted.
  const ports = ['waves.list', 'waves.progress', 'waves.run', 'waves.send', 'waves.start', 'waves.stop'];
  const derived = [
    ...commandKeys().filter((name) => APPLICATION_COMMAND_DEFINITIONS[name].web),
    ...ports,
  ].sort();
  assert.deepEqual(webCardCommands(), derived);
  for (const port of ports) {
    assert.equal(Object.hasOwn(APPLICATION_COMMAND_DEFINITIONS, port), false,
      `${port} is a direct port, never a table entry`);
  }
});

test('ordinaryMcpToolNames: served order is deterministic and its set is byte-stable against the artifact', () => {
  const names = ordinaryMcpToolNames();
  assert.deepEqual(names, ordinaryMcpToolNames(), 'the served order is deterministic');
  assert.deepEqual([...names].sort(), mcpApplicationToolNames(),
    'the served set equals mcpApplicationToolNames()');
  assert.deepEqual([...names].sort(), artifact.profiles['mcp.application'],
    'the served set is byte-stable against the committed mcp.application profile');
  assert.equal(names.length, artifact.counts.mcpApplicationTools);
  assert.ok(names.includes('baton_swarm_list'), 'the swarm family rides the ordinary surface');
  assert.ok(!names.some((name) => /shutdown|fleet_/u.test(name)), 'no host-lifecycle or fleet_ tool');
});

test('combinedMcpToolNames: byte-stable against the artifact and a superset of the ordinary set', () => {
  const names = combinedMcpToolNames();
  assert.deepEqual(names, artifact.profiles['mcp.combined'],
    'the combined set is byte-stable against the committed mcp.combined profile');
  assert.equal(names.length, artifact.counts.mcpCombinedTools);
  assert.equal(new Set(names).size, names.length, 'no duplicate tool names');
  const ordinary = new Set([...ordinaryMcpToolNames()].sort());
  for (const name of ordinary) assert.ok(names.includes(name), `${name} stays served on combined`);
});

test('applicationCardCommands: table keys first, then the M4b canonical names, disjoint and derived', () => {
  const commands = applicationCardCommands();
  const keys = commandKeys();
  assert.deepEqual(commands.slice(0, keys.length), keys, 'the table keys lead in insertion order');
  const canonicalTail = commands.slice(keys.length);
  assert.equal(new Set([...keys]).intersection(new Set(canonicalTail)).size, 0,
    'the canonical names are never table keys (docs/36 §9 M4b)');
  const byKey = new Map(APPLICATION_SEMANTIC_REGISTRY.canonicalOperations.map((op) => [op.key, op]));
  for (const name of canonicalTail) {
    const operation = byKey.get(name);
    assert.ok(operation, `${name} is a registered canonical operation`);
    assert.equal(operation.profile, 'ordinary', `${name} is an ordinary operation`);
  }
});

test('mockApplicationCard: a table-derived card that satisfies the real server constructor', () => {
  const card = mockApplicationCard('repo-mock');
  assert.deepEqual(card, { schemaVersion: 1, repoId: 'repo-mock', commands: applicationCardCommands() });
  for (const [name, definition] of Object.entries(APPLICATION_COMMAND_DEFINITIONS)) {
    if (definition.web || definition.mcp) {
      assert.ok(card.commands.includes(name), `${name} is advertised to every admitting surface`);
    }
  }
  const coordination = Object.fromEntries(
    ['admitMcpCall', 'completeMcpCall', 'failMcpCall', 'mcpCall', 'recordMcpAudit']
      .map((method) => [method, async () => ({})]),
  );
  const common = {
    coordinator: {}, coordination,
    principal: {
      userId: 'surface-truth-test', sessionId: 'surface-truth-test',
      capabilities: ['observe', 'control', 'approve', 'emergency_stop'],
      repoIds: ['repo-mock'], expiresAt: '9999-01-01T00:00:00.000Z', revoked: false,
    },
    repoIds: ['repo-mock'],
    application: {
      repoId: 'repo-mock', card: () => ({ ...card }),
      command: async () => ({}), authorizeReplay: async () => true,
    },
    applicationOwned: false,
  };
  assert.equal(new McpFleetServer({ ...common, surface: 'application' }).toolDefinitions.length,
    ordinaryMcpToolNames().length);
  assert.equal(new McpFleetServer({ ...common, surface: 'combined' }).toolDefinitions.length,
    combinedMcpToolNames().length);
});
